suitenumerique/meet

- src/helm/env.d/dev/secrets.enc.yaml
- src/helm/meet/templates/secrets.yaml
Fix helm secret to be abble to use titl on dev
> 🔧(helm) fix helm chart

- src/frontend/src/App.tsx
- src/frontend/src/layout/Screen.tsx
the app crashed on screen changes, I don't quite get why right now, must be missing something… but at least this goes around the issue. Will check better later.
> 🐛(frontend) have a suspense fallback

- src/frontend/panda.config.ts
- src/frontend/src/components/Feedback.tsx
- src/frontend/src/layout/Header.tsx
- src/frontend/src/locales/de/global.json
- src/frontend/src/locales/en/global.json
- src/frontend/src/locales/fr/global.json
- src/frontend/src/primitives/Button.tsx
this is just a link to an external url that is, for now, hardcoded as our deploys dont have frontend env vars right now
Will merge when the Grist is ready @CamCaz1 :innocent:
> ✨(frontend) new feedback link in header

- src/frontend/src/features/rooms/components/Conference.tsx
- src/frontend/src/features/rooms/index.ts
- src/frontend/src/features/rooms/routes/Feedback.tsx
- src/frontend/src/layout/Header.tsx
- src/frontend/src/locales/de/rooms.json
- src/frontend/src/locales/en/global.json
- src/frontend/src/locales/en/rooms.json
- src/frontend/src/locales/fr/global.json
- src/frontend/src/locales/fr/rooms.json
- src/frontend/src/primitives/Button.tsx
- src/frontend/src/routes.ts
just adding a view on call end so that the user remembers about giving feedback
> Feedback details

- src/backend/core/analytics.py
- src/backend/core/api/viewsets.py
- src/backend/core/authentication/backends.py
- src/backend/core/authentication/views.py
- src/backend/core/models.py
- src/backend/core/tests/test_analytics.py
- src/backend/core/tests/test_models_users.py
- src/backend/meet/settings.py
- src/backend/pyproject.toml
- src/helm/env.d/dev/values.meet.yaml.gotmpl
- src/helm/env.d/production/values.meet.yaml.gotmpl
- src/helm/env.d/staging/values.meet.yaml.gotmpl
Track (anonymously) user behavior.
Please refer to the commit description for details.
We are using a pre-market fit product to analyze user interactions and product
features. This product was developed by a French.
> Add analytics

- src/backend/pyproject.toml
- src/frontend/package-lock.json
- src/frontend/package.json
- src/helm/env.d/preprod/values.meet.yaml.gotmpl
- src/helm/env.d/production/values.meet.yaml.gotmpl
- src/mail/package.json
> 🔖(minor) bump release to 0.1.3

- .github/workflows/meet.yml
- src/frontend/.eslintrc.cjs
- src/frontend/package-lock.json
- src/frontend/package.json
- src/frontend/src/App.tsx
- src/frontend/src/api/queryClient.ts
- src/frontend/src/components/ErrorScreen.tsx
- src/frontend/src/features/auth/utils/authUrl.ts
- src/frontend/src/features/auth/utils/silentLogin.ts
- src/frontend/src/features/home/routes/Home.tsx
- src/frontend/src/features/rooms/api/ApiRoom.ts
- src/frontend/src/features/rooms/api/createRoom.ts
- src/frontend/src/features/rooms/components/Conference.tsx
- src/frontend/src/features/rooms/routes/Feedback.tsx
- src/frontend/src/layout/Header.tsx
- src/frontend/src/primitives/PopoverList.tsx
- src/frontend/src/utils/livekit.ts
Enhance code format
Configure prettier, with the most minimalist configuration ever.
> Add prettier format and check command

- src/frontend/src/features/rooms/livekit/components/controls/ChatToggle.tsx
- src/frontend/src/features/rooms/livekit/components/controls/Participants/ParticipantsList.tsx
- src/frontend/src/features/rooms/livekit/components/controls/Participants/ParticipantsToggle.tsx
- src/frontend/src/features/rooms/livekit/constants/events.ts
- src/frontend/src/features/rooms/livekit/prefabs/ControlBar.tsx
- src/frontend/src/features/rooms/livekit/prefabs/VideoConference.tsx
- src/frontend/src/locales/de/rooms.json
- src/frontend/src/locales/en/rooms.json
- src/frontend/src/locales/fr/rooms.json
- src/frontend/src/primitives/Button.tsx
- src/frontend/src/primitives/Dialog.tsx
- src/frontend/src/stores/participants.ts
- src/frontend/src/utils/capitalize.ts
Add the list of participants
Implement a basic version of the participant list feature. This initial
version provides a starting point but lacks several key details needed
for full usability.
> Bootstrap a participants list

- src/backend/pyproject.toml
- src/frontend/package-lock.json
- src/frontend/package.json
- src/helm/env.d/preprod/values.meet.yaml.gotmpl
- src/helm/env.d/production/values.meet.yaml.gotmpl
- src/mail/package-lock.json
- src/mail/package.json
> 🔖(minor) bump release to 0.1.4

- src/frontend/src/features/home/components/LaterMeetingDialog.tsx
- src/frontend/src/features/home/routes/Home.tsx
- src/frontend/src/locales/de/home.json
- src/frontend/src/locales/en/home.json
- src/frontend/src/locales/fr/home.json
Inspired by the Google Meet user experience.
A simple UX for scheduling meetings was requested by some users. This is a quick and basic poc to validate the UX in a production environment. If it gains traction, it will be refined and consolidated.
> ✨(frontend) create meeting for later

- src/backend/core/utils.py
- src/frontend/panda.config.ts
- src/frontend/src/components/Avatar.tsx
- src/frontend/src/features/rooms/livekit/components/FocusLayout.tsx
- src/frontend/src/features/rooms/livekit/components/ParticipantPlaceholder.tsx
- src/frontend/src/features/rooms/livekit/components/ParticipantTile.tsx
- src/frontend/src/features/rooms/livekit/components/controls/Participants/ParticipantsList.tsx
- src/frontend/src/features/rooms/livekit/hooks/useResizeObserver.ts
- src/frontend/src/features/rooms/livekit/prefabs/VideoConference.tsx
- src/frontend/src/features/rooms/utils/getParticipantColor.ts
Enhance participants' placeholders based on @arnaud-robin's feedback.
it closes #89 
Some details could be refined, but this is a solid first iteration.
> Enhance participant placeholder

- src/backend/core/utils.py
- src/frontend/panda.config.ts
- src/frontend/src/components/Avatar.tsx
- src/frontend/src/features/rooms/components/ActiveSpeaker.tsx
- src/frontend/src/features/rooms/livekit/api/buildServerApiUrl.ts
- src/frontend/src/features/rooms/livekit/api/fetchServerApi.ts
- src/frontend/src/features/rooms/livekit/api/muteParticipant.ts
- src/frontend/src/features/rooms/livekit/components/controls/Participants/ParticipantListItem.tsx
- src/frontend/src/features/rooms/livekit/components/controls/Participants/ParticipantsList.tsx
- src/frontend/src/features/rooms/livekit/hooks/useRoomData.ts
- src/frontend/src/locales/de/rooms.json
- src/frontend/src/locales/en/rooms.json
- src/frontend/src/locales/fr/rooms.json
- src/frontend/src/utils/livekit.ts
Mute remote participants
Thx Nathan Vasse for his help on the css animation.
Raw function feature, allowing participants muting each other.
> Mute remote participant

- src/frontend/src/features/rooms/components/Conference.tsx
Troubleshoot disconnection bug.
One hypothesis, no real conviction on this one.
> avoid disabling request

- src/frontend/src/locales/en/notifications.json
- src/frontend/src/locales/en/rooms.json
> 🌐(frontend) enhance few English traductions

- src/backend/pyproject.toml
- src/frontend/package-lock.json
- src/frontend/package.json
- src/helm/env.d/preprod/values.meet.yaml.gotmpl
- src/helm/env.d/production/values.meet.yaml.gotmpl
- src/mail/package-lock.json
- src/mail/package.json
> 🔖(minor) bump release to 0.1.5

- src/frontend/src/features/notifications/MainNotificationToast.tsx
- src/frontend/src/features/rooms/components/Conference.tsx
- src/frontend/src/features/rooms/components/Join.tsx
- src/frontend/src/features/rooms/livekit/components/controls/LeaveButton.tsx
- src/frontend/src/features/rooms/livekit/components/controls/ScreenShareToggle.tsx
- src/frontend/src/features/rooms/livekit/components/controls/SelectToggleDevice.tsx
- src/frontend/src/features/rooms/livekit/prefabs/ControlBar.tsx
- src/frontend/src/locales/de/rooms.json
- src/frontend/src/locales/en/rooms.json
- src/frontend/src/locales/fr/rooms.json
- src/frontend/src/primitives/MenuList.tsx
Enhance the control bar to improve user experience and visual consistency.
- Fix the user experience for the audio and video input buttons.
- Align the quit and share screen buttons for layout consistency.
> Enhance the Control bar

- src/frontend/package-lock.json
- src/frontend/package.json
- src/frontend/src/App.tsx
- src/frontend/src/features/auth/api/useUser.tsx
- src/frontend/src/features/home/components/LaterMeetingDialog.tsx
- src/frontend/src/features/home/routes/Home.tsx
- src/frontend/src/features/rooms/components/Conference.tsx
- src/frontend/src/features/rooms/components/InviteDialog.tsx
- src/frontend/src/features/rooms/livekit/components/controls/ChatToggle.tsx
- src/frontend/src/features/rooms/livekit/components/controls/HandToggle.tsx
- src/frontend/src/features/rooms/livekit/components/controls/LeaveButton.tsx
- src/frontend/src/features/rooms/livekit/components/controls/Participants/HandRaisedListItem.tsx
- src/frontend/src/features/rooms/livekit/components/controls/Participants/LowerAllHandsButton.tsx
- src/frontend/src/features/rooms/livekit/components/controls/Participants/ParticipantListItem.tsx
- src/frontend/src/features/rooms/livekit/components/controls/Participants/ParticipantsList.tsx
- src/frontend/src/features/rooms/livekit/components/controls/Participants/ParticipantsToggle.tsx
- src/frontend/src/features/rooms/livekit/components/controls/ScreenShareToggle.tsx
- src/frontend/src/layout/Header.tsx
- src/frontend/src/locales/de/rooms.json
- src/frontend/src/locales/en/rooms.json
- src/frontend/src/locales/fr/rooms.json
Set-up PostHog to enhance our product analysis capabilities.
Use the saas offer hosted in Europe, as Tchap does.
> Set-up PostHog

- src/frontend/index.html
- src/frontend/src/features/home/components/JoinMeetingDialog.tsx
- src/frontend/src/locales/de/global.json
- src/frontend/src/locales/en/global.json
- src/frontend/src/locales/en/home.json
- src/frontend/src/locales/en/rooms.json
- src/frontend/src/locales/en/settings.json
- src/frontend/src/locales/fr/global.json
- src/frontend/src/locales/fr/home.json
- src/frontend/src/locales/fr/rooms.json
In alignment with French government guidelines, ensuring no English terms slip through.
> Visio renaming

- src/frontend/src/App.tsx
- src/frontend/src/features/analytics/hooks/useAnalytics.tsx
- src/frontend/src/features/auth/api/useUser.tsx
- src/frontend/src/layout/Header.tsx
Decouple the code from the PostHog dependency by wrapping it in a custom hook and several utility functions. This enhances code maintainability and separation of concerns.
> ♻️(frontend) encapsulate PostHog logic in dedicated functions

- src/frontend/package-lock.json
- src/frontend/package.json
- src/frontend/src/App.tsx
- src/frontend/src/features/auth/api/useUser.tsx
- src/frontend/src/features/support/hooks/useSupport.tsx
- src/frontend/src/layout/Header.tsx
> Add support

- src/backend/pyproject.toml
- src/frontend/package-lock.json
- src/frontend/package.json
- src/helm/env.d/preprod/values.meet.yaml.gotmpl
- src/helm/env.d/production/values.meet.yaml.gotmpl
- src/mail/package-lock.json
- src/mail/package.json
> 🔖(minor) bump release to 0.1.6

- src/helm/env.d/production/values.meet.yaml.gotmpl
- src/helm/extra/templates/redirect.yaml
- src/helm/helmfile.yaml
Add ingress in order to migrate from meet.numerique.gouv.fr to visio.numerique.gouv.fr
> 🔒️(helm) change domainon production

- src/helm/env.d/production/values.meet.yaml.gotmpl
- src/helm/env.d/staging/values.meet.yaml.gotmpl
Newly introduced ingress for PostHog were misconfigured, oopsie. Here is the fix.
> 🐛(helm) fix certificates configuration

- src/frontend/src/features/auth/api/fetchUser.ts
- src/frontend/src/features/auth/api/useUser.tsx
closes https://github.com/numerique-gouv/meet/issues/144
> Fix bug disconnection

- .sops.yaml
- src/helm/env.d/dev/secrets.enc.yaml
> 🔐(tilt) add Samuel's key

- src/backend/core/api/viewsets.py
Be more Pythonist simplifying, try except while tracking when user is getting a room.
> ♻️(backend) refactor try/except when getting a room

- src/backend/core/authentication/backends.py
- src/backend/core/migrations/0006_merge_duplicate_users.py
- src/backend/core/tests/authentication/test_backends.py
- src/backend/meet/settings.py
Inspired by @sampaccoud and @qbey works.
Catching up with People and Impress recent's updates.
> Refactor authentication

- src/backend/core/api/__init__.py
- src/frontend/src/api/useConfig.ts
> Expose recording config to the frontend

- src/backend/core/api/permissions.py
- src/backend/core/api/viewsets.py
- src/backend/core/models.py
- src/backend/core/recording/event/__init__.py
- src/backend/core/recording/event/authentication.py
- src/backend/core/recording/event/exceptions.py
- src/backend/core/recording/event/parsers.py
- src/backend/core/tests/recording/event/test_authentication.py
- src/backend/core/tests/recording/event/test_parsers.py
- src/backend/core/tests/recording/test_api_recordings_storage_hook.py
- src/backend/core/tests/test_models_recording.py
- src/backend/meet/settings.py
Enable automatic status updates when recordings are saved to object storage.
Implement a secure webhook endpoint to process recording completion notifications from MinIO.
> Minio webhook

- src/frontend/panda.config.ts
- src/frontend/src/features/home/components/IntroSlider.tsx
- src/frontend/src/features/home/routes/Home.tsx
- src/frontend/src/layout/Header.tsx
> Fix responsive

- src/frontend/src/features/home/components/IntroSlider.tsx
- src/frontend/src/features/home/routes/Home.tsx
- src/frontend/src/locales/en/global.json
- src/frontend/src/locales/en/home.json
- src/frontend/src/locales/fr/home.json
Based on Samuel's feedbacks, adjust few details.
> 💄(frontend) adjust home based on Sam feedbacks

- .github/workflows/docker-hub.yml
- bin/Tiltfile
- src/helm/env.d/dev/values.meet.yaml.gotmpl
- src/helm/env.d/staging/values.meet.yaml.gotmpl
- src/helm/extra/templates/summary_keydb.yaml
- src/helm/meet/templates/_helpers.tpl
- src/helm/meet/templates/celery_deployment.yaml
- src/helm/meet/templates/summary_deployment.yaml
- src/helm/meet/templates/summary_secrets.yaml
- src/helm/meet/templates/summary_svc.yaml
- src/helm/meet/values.yaml
- src/summary/Dockerfile
- src/summary/compose.yaml
- src/summary/pyproject.toml
- src/summary/summary/__init__.py
- src/summary/summary/celery_worker.py
- src/summary/summary/config.py
- src/summary/summary/main.py
- src/summary/summary/prompt.py
- src/summary/summary/security.py
Introducing a summary service with the following characteristics:
- Notified by a Backend event.
- Single worker processing to manage Whisper endpoint load constraints
- Works with any API following OpenAI design.
The initial deployment will target a very limited user base for behavior analysis.
I want to be super cautious, while scaling this feature.
The current design prioritizes reliability and retry capabilities over optimization. Future phases will include:
- Scaling improvements
- Implementation of async queue system in Whisper endpoints.
If the isolated microservice architecture proves unnecessary, code will be refactored into a Django app.
**I haven't written test yet 💥😢 and a feature without unit tests doesn't exist … will do asap**
> Summary service

- src/backend/pyproject.toml
- src/frontend/package-lock.json
- src/frontend/package.json
- src/helm/env.d/production/values.meet.yaml.gotmpl
- src/mail/package-lock.json
- src/mail/package.json
> 🔖(patch) bump release to 0.1.9

- src/backend/pyproject.toml
- src/frontend/package-lock.json
- src/frontend/package.json
- src/helm/env.d/production/values.meet.yaml.gotmpl
- src/mail/package-lock.json
- src/mail/package.json
I made a mistake, and forgot to set summary and celery deployment to 0 replicas.
> 🔖(patch) bump release to 0.1.10

- src/backend/core/authentication/views.py
- src/backend/meet/settings.py
> Misc fixes backend configuration

- src/helm/env.d/dev/values.meet.yaml.gotmpl
- src/helm/env.d/staging/values.meet.yaml.gotmpl
> Update summary service adresses 

- src/backend/meet/settings.py
- src/helm/env.d/production/values.meet.yaml.gotmpl
- src/helm/env.d/staging/values.meet.yaml.gotmpl
Connect Visio microservice with docs endpoint, and release it in production.
Commits are WIP, I need help from @rouja to update secrets.
> Release AI in staging and prod

- src/backend/pyproject.toml
- src/frontend/package-lock.json
- src/frontend/package.json
- src/helm/env.d/production/values.meet.yaml.gotmpl
- src/mail/package-lock.json
Weekly release, responsiveness is still under construction.
> 🔖(patch) bump release to 0.1.11

- src/mail/package.json
- src/summary/summary/core/celery_worker.py
Urgent fix for the incoming demo
> Fix summary microservice

- src/backend/pyproject.toml
- src/frontend/package-lock.json
- src/frontend/package.json
- src/helm/env.d/production/values.meet.yaml.gotmpl
- src/mail/package-lock.json
- src/mail/package.json
Release a fix while calling Docs backend API.
> 🔖(patch) bump release to 0.1.12

- src/frontend/src/features/rooms/livekit/components/Effects.tsx
- src/frontend/src/features/rooms/livekit/components/blur/BackgroundBlurCustomProcessor.ts
- src/frontend/src/features/rooms/livekit/components/blur/BackgroundBlurTrackProcessorJsWrapper.ts
- src/frontend/src/features/rooms/livekit/components/blur/TimerWorker.ts
- src/frontend/src/features/rooms/livekit/components/blur/index.ts
- src/frontend/src/locales/en/rooms.json
- src/frontend/src/locales/fr/rooms.json
The library we use to make video filtering on the project is [track-processor-js](https://github.com/livekit/track-processors-js). This vendor is not compatible with browser other than Chrome and Edge. 
- This vendor uses GPU computing to run inference, which is not possible on Firefox.
- This vendor uses MediaStreamTrackProcessor and MediaStreamTrackGenerator that are not available on Firefox.
Knowing that I had to make a custom implementation of video filtering compatible with Firefox, we use https://ai.google.dev/edge/mediapipe/solutions/guide to run inference with the https://storage.googleapis.com/mediapipe-models/image_segmenter/selfie_segmenter_landscape/float16/latest/selfie_segmenter_landscape.tflit model. The inferences run on CPU with gives inferior performances. 
In order to …
> ✨(front) add blurring support on Firefox

- src/frontend/src/features/rooms/livekit/components/controls/Options/OptionsMenuItems.tsx
- src/frontend/src/features/rooms/livekit/components/controls/Participants/ParticipantListItem.tsx
- src/frontend/src/features/rooms/livekit/components/controls/Participants/ParticipantsList.tsx
Fix minor warnings, which were spamming the console. Please refer to my commits for more information.
> Fix misc Warning

- src/frontend/src/features/rooms/livekit/components/controls/Options/OptionsMenuItems.tsx
- src/frontend/src/features/rooms/livekit/prefabs/ControlBar/MobileControlBar.tsx
- src/frontend/src/locales/de/rooms.json
- src/frontend/src/locales/en/rooms.json
- src/frontend/src/locales/fr/rooms.json
Feedback is a mass noun.
Spotted by @bvhme
> ✏️(frontend) fix feedback-s

- src/frontend/src/features/rooms/livekit/components/controls/Options/OptionsButton.tsx
- src/frontend/src/features/rooms/livekit/components/controls/Options/OptionsMenuItems.tsx
- src/frontend/src/features/rooms/livekit/components/controls/ScreenShareToggle.tsx
- src/frontend/src/features/rooms/livekit/components/controls/SelectToggleDevice.tsx
- src/frontend/src/features/rooms/livekit/prefabs/ControlBar/DesktopControlBar.tsx
- src/frontend/src/primitives/Box.tsx
- src/frontend/src/primitives/Menu.tsx
- src/frontend/src/primitives/MenuList.tsx
- src/frontend/src/primitives/Separator.tsx
- src/frontend/src/primitives/menuRecipe.ts
> Fix minor ui issues

- src/frontend/src/features/home/routes/Home.tsx
Forgot how panda css is amazing. They provide all kinds of utilities, and few for accessibility. Amazing!
> ♻️(frontend) use pandas utilities

- src/frontend/src/features/rooms/components/Join.tsx
- src/frontend/src/locales/de/rooms.json
- src/frontend/src/locales/en/rooms.json
- src/frontend/src/locales/fr/rooms.json
- src/frontend/src/primitives/Form.tsx
- src/frontend/src/primitives/H.tsx
[Enhancements proposed in a short loom](https://www.loom.com/share/201fbaf367e44b37ac159ca6423db5d2)
- Always enable camera/mic by default (like Google Meet)
- Fix video state transitions and add visual feedback
- Simplify form using React Aria components
- Reduce shadow intensity for better visual balance
It closes #324
> 🚸(frontend) improve prejoin UX

- src/frontend/src/layout/Footer.tsx
- src/frontend/src/locales/de/global.json
- src/frontend/src/locales/en/global.json
- src/frontend/src/locales/fr/global.json
Great idea suggested by @fflorent — totally worth it!
> 🔍️(frontend) add link to the source code in the footer

- src/frontend/src/features/rooms/components/Join.tsx
- src/frontend/src/features/rooms/livekit/components/effects/EffectsConfiguration.tsx
Few nit-picking elements about the newly introduced prejoin screen. 
Most of them are not strictly essential, except the ones concerning UX enhancements.
> Nit-pitcking on Join screen

- .github/workflows/deploy.yml
- .github/workflows/docker-hub.yml
The secrets are not managed in the folder anymore.
> 💚(github) remove secret fetch

- src/frontend/Dockerfile
- src/frontend/src/features/notifications/MainNotificationToast.tsx
- src/frontend/src/features/notifications/NotificationType.ts
- src/frontend/src/features/notifications/components/ToastMessageReceived.tsx
- src/frontend/src/features/notifications/components/ToastMuted.tsx
- src/frontend/src/features/notifications/components/ToastRegion.tsx
- src/frontend/src/features/rooms/components/Conference.tsx
- src/frontend/src/features/rooms/livekit/api/muteParticipant.ts
- src/frontend/src/features/rooms/livekit/hooks/useRaisedHand.ts
- src/frontend/src/features/rooms/livekit/hooks/useRoomData.ts
- src/frontend/src/locales/de/notifications.json
- src/frontend/src/locales/en/notifications.json
- src/frontend/src/locales/fr/notifications.json
- src/frontend/src/stores/notifications.ts
When someone mute you :
https://github.com/user-attachments/assets/00793a55-5dd9-47a4-a039-f5df400ed343
> Notify the user when her was muted.

- src/frontend/src/features/rooms/livekit/components/ParticipantTileFocus.tsx
Auto-hides participant tile controls after 3 seconds of cursor inactivity to reduce visual clutter. Controls reappear on cursor movement.
https://github.com/user-attachments/assets/49baf276-990c-423f-b7b2-dd95f3d8aee0
> 🚸(frontend) auto-hide participant controls after 3s of inactivity

- src/frontend/src/features/notifications/MainNotificationToast.tsx
- src/frontend/src/features/notifications/NotificationDuration.ts
- src/frontend/src/features/notifications/NotificationPayload.ts
- src/frontend/src/features/notifications/NotificationType.ts
- src/frontend/src/features/rooms/livekit/api/muteParticipant.ts
- src/frontend/src/features/rooms/livekit/components/ReactionPortal.tsx
- src/frontend/src/features/rooms/livekit/components/controls/ReactionsToggle.tsx
- src/frontend/src/features/rooms/livekit/prefabs/ControlBar/DesktopControlBar.tsx
- src/frontend/src/locales/de/notifications.json
- src/frontend/src/locales/de/rooms.json
- src/frontend/src/locales/en/notifications.json
- src/frontend/src/locales/en/rooms.json
- src/frontend/src/locales/fr/notifications.json
- src/frontend/src/locales/fr/rooms.json
- src/frontend/src/primitives/Menu.tsx
Implement a new reactions system allowing users to send quick emoji responses during video calls.
This feature is present in most visio softwares and requested by some users.
- Add ReactionsButton to control bar
with emoji selection
- Create notification payload and toast
for reaction events
- Support floating emoji animations
- Add sound notification for reactions
- Update localization files with new translations
> ✨(frontend) add emoji reactions feature

- src/backend/pyproject.toml
- src/frontend/package-lock.json
- src/frontend/package.json
- src/mail/package-lock.json
- src/mail/package.json
- src/sdk/package-lock.json
- src/sdk/package.json
- src/summary/pyproject.toml
Release emoji reactions.
Calendar SDK integrations.
Few enhancements:
- avoid infinite mirror loop
- auto-lower hand of an active speaker
- fix message notifications
> 🔖(minor) bump release to 0.1.14

- src/frontend/src/layout/Footer.tsx
- src/frontend/src/locales/de/global.json
- src/frontend/src/locales/en/global.json
- src/frontend/src/locales/fr/global.json
Would help partner make the tool works in their paradigm.
> Add technical notice

- src/frontend/src/features/auth/api/useUser.tsx
- src/frontend/src/features/auth/index.ts
- src/frontend/src/features/notifications/components/ToastMessageReceived.tsx
- src/frontend/src/features/rooms/components/Rating.tsx
- src/frontend/src/features/rooms/livekit/components/Transcript.tsx
- src/frontend/src/features/rooms/livekit/components/controls/ReactionsToggle.tsx
- src/frontend/src/features/rooms/livekit/components/controls/TranscriptToggle.tsx
- src/frontend/src/features/rooms/livekit/components/effects/EffectsConfiguration.tsx
- src/frontend/src/features/settings/components/SettingsDialog.tsx
- src/frontend/src/features/settings/components/tabs/AccountTab.tsx
- src/frontend/src/layout/Header.tsx
- src/frontend/src/locales/de/rooms.json
- src/frontend/src/locales/en/rooms.json
- src/frontend/src/locales/fr/rooms.json
Filled limited time between meetings to address minor issues.
> Misc fixes

- src/frontend/src/features/notifications/MainNotificationToast.tsx
- src/frontend/src/features/notifications/utils.ts
- src/frontend/src/features/rooms/hooks/useWaitingParticipants.ts
- src/frontend/src/features/rooms/livekit/api/lowerHandParticipant.ts
- src/frontend/src/features/rooms/livekit/components/controls/Participants/ParticipantsList.tsx
- src/frontend/src/features/rooms/utils/getParticipantColor.ts
- src/frontend/src/features/rooms/utils/safeParseMetadata.tsx
> Handle cautious user input

- src/frontend/src/features/rooms/components/Join.tsx
- src/frontend/src/locales/en/rooms.json
- src/frontend/src/locales/fr/rooms.json
- src/frontend/src/primitives/Spinner.tsx
Follow robin's design.
https://github.com/user-attachments/assets/11888986-2867-403a-93f3-6c1ab6822639
> Enhance loading animation

- src/frontend/src/components/FeedbackBanner.tsx
- src/frontend/src/features/rooms/livekit/components/MutedMicIndicator.tsx
- src/frontend/src/features/rooms/livekit/components/controls/ChatToggle.tsx
- src/frontend/src/features/rooms/livekit/components/controls/Options/OptionsButton.tsx
- src/frontend/src/features/rooms/livekit/components/controls/ReactionsToggle.tsx
- src/frontend/src/features/rooms/livekit/prefabs/ControlBar/DesktopControlBar.tsx
- src/frontend/src/features/rooms/livekit/prefabs/ControlBar/MoreOptions.tsx
- src/frontend/src/locales/en/global.json
- src/frontend/src/locales/fr/global.json
- src/frontend/src/primitives/Switch.tsx
Enhance accessibility, first batch of improvements.
> Accessibility

- src/frontend/i18next-parser.config.json
- src/frontend/src/i18n/init.ts
- src/frontend/src/i18n/useLanguageLabels.ts
- src/frontend/src/locales/nl/global.json
- src/frontend/src/locales/nl/home.json
- src/frontend/src/locales/nl/notifications.json
- src/frontend/src/locales/nl/rooms.json
- src/frontend/src/locales/nl/sdk.json
- src/frontend/src/locales/nl/settings.json
Adding a Dutch translation to Meet.
I've added Dutch to the langauge selection system and duplicated the English folder and replaced the messages with Dutch texts.
> Adding Dutch translation for the frontend

- src/frontend/src/features/legalsTerms/Accessibility.tsx
- src/frontend/src/features/legalsTerms/LegalTermsRoute.tsx
- src/frontend/src/features/legalsTerms/TermsOfService.tsx
- src/frontend/src/layout/Footer.tsx
- src/frontend/src/layout/Header.tsx
- src/frontend/src/layout/Screen.tsx
- src/frontend/src/locales/de/accessibility.json
- src/frontend/src/locales/de/global.json
- src/frontend/src/locales/de/legals.json
- src/frontend/src/locales/de/termsOfService.json
- src/frontend/src/locales/en/accessibility.json
- src/frontend/src/locales/en/global.json
- src/frontend/src/locales/en/legals.json
- src/frontend/src/locales/en/termsOfService.json
- src/frontend/src/locales/fr/accessibility.json
- src/frontend/src/locales/fr/global.json
- src/frontend/src/locales/fr/legals.json
- src/frontend/src/locales/fr/termsOfService.json
- src/frontend/src/locales/nl/accessibility.json
- src/frontend/src/locales/nl/global.json
- src/frontend/src/locales/nl/legals.json
- src/frontend/src/locales/nl/termsOfService.json
- src/frontend/src/primitives/A.tsx
- src/frontend/src/routes.ts
Necessary pages for accessibility reasons
Introduce basic pages following a common template across La Suite products.
> Add Legal terms pages

- src/backend/pyproject.toml
- src/frontend/package-lock.json
- src/frontend/package.json
- src/mail/package-lock.json
- src/mail/package.json
- src/sdk/package-lock.json
- src/sdk/package.json
- src/summary/pyproject.toml
Release private and restricted rooms.
> 🔖(minor) bump release to 0.1.15

- Makefile
- compose.yml
- src/frontend/Dockerfile
Run frontend when calling `make bootstrap`
It is related to https://github.com/suitenumerique/meet/issues/363.
> Fix bootstrap

- README.md
Clarify the license, and avoid any enterprise-like vocabulary or expression.
Thx @bzg
> 📝(readme) integrate feedbacks from open-source specialist

- LICENSES/LICENSE.Etalab-2.0.md
- LICENSES/LICENSE.MIT.md
following @bzg advice, updates our licenses.
> 📄(license) update license following expert review

- src/frontend/src/features/legalsTerms/Accessibility.tsx
- src/frontend/src/features/legalsTerms/LegalTermsRoute.tsx
- src/frontend/src/features/legalsTerms/TermsOfService.tsx
- src/frontend/src/locales/de/accessibility.json
- src/frontend/src/locales/de/legals.json
- src/frontend/src/locales/de/termsOfService.json
- src/frontend/src/locales/en/accessibility.json
- src/frontend/src/locales/en/legals.json
- src/frontend/src/locales/en/termsOfService.json
- src/frontend/src/locales/fr/accessibility.json
- src/frontend/src/locales/fr/legals.json
- src/frontend/src/locales/fr/termsOfService.json
- src/frontend/src/locales/nl/accessibility.json
- src/frontend/src/locales/nl/legals.json
- src/frontend/src/locales/nl/termsOfService.json
following legal team's advices, updates our legal terms.
> 📄(legal) update legal notice following expert review

- src/frontend/src/features/rooms/livekit/components/blur/BackgroundBlurTrackProcessorJsWrapper.ts
accross -> across
Description...
- [] item 1...
- [] item 2...
> chore: update BackgroundBlurTrackProcessorJsWrapper.ts

- .gitmodules
Secrets are not in-use anymore in the project, dead code.
It closes #400
> ⚰️(secrets) remove useless submodule

- src/frontend/panda.config.ts
- src/frontend/src/components/Avatar.tsx
- src/frontend/src/components/FeedbackBanner.tsx
- src/frontend/src/features/home/components/IntroSlider.tsx
- src/frontend/src/features/home/routes/Home.tsx
- src/frontend/src/primitives/A.tsx
Updated styling system to implement the official French font used across all La Suite products. This enhances brand consistency and improves the visual identity alignment with other government digital services.
> 💄(frontend) use official Marianne font

- src/frontend/src/locales/nl/rooms.json
Oopsi, forgot some dutch content when resolving conflicts while merging traductions. Fixed.
> 🌐(frontend) add missing dutch content

- src/summary/summary/api/route/tasks.py
- src/summary/summary/core/celery_worker.py
Switch from insanely-fast-whisper to WhisperX for transcription services, gaining word-level granularity not available with FlashAttention in previous API. Whisper was packaged in FastAPI image with basic diarization and speaker-segment association capabilities.
Implementation prioritized speed to market over testing. Future iterations will enhance diarization quality and add proper test coverage. API consumers should expect behavioral differences and new capabilities.
Code have been tested using this branch https://github.com/lebaudantoine/whisper-openai-api/tree/whisperx, and this image [tag](https://hub.docker.com/repository/docker/lasuite/whisper-api/tags/whisperx-002/sha256-a5693ff2182546d61f6a287997c9dc006cb691ed8ff4f5738c28365bedc1b0fa)
> 💥(summary) replace Whisper with WhisperX for transcription

- docs/installation.md
Give more insight to which options are available for configuration of the backend
Add a table to the installation docs of all the available environmental options.
> 📝(docs) describe environmental options for meet backend

- src/backend/pyproject.toml
- src/frontend/package-lock.json
- src/frontend/package.json
- src/mail/package-lock.json
- src/mail/package.json
- src/sdk/package-lock.json
- src/sdk/package.json
- src/summary/pyproject.toml
> 🔖(minor) bump release to 0.1.17

- src/frontend/src/features/sdk/routes/CreateMeetingButton.tsx
- src/frontend/src/features/sdk/utils/PopupManager.ts
- src/frontend/src/features/sdk/utils/types.ts
- src/sdk/consumer/src/App.tsx
- src/sdk/library/src/Types.ts
- src/sdk/library/src/create/VisioCreateButton.tsx
Notify iframe's parent while integrating Visio when state is cleared. Requested by Eleonore.
> 🩹(frontend) fix missing notification when state is clear

- src/frontend/package-lock.json
- src/frontend/package.json
- src/sdk/consumer/package.json
- src/sdk/library/package.json
- src/sdk/package-lock.json
Update vite dependency, related to #417
> Update vite for security reason

- src/frontend/src/features/sdk/routes/CreateMeetingButton.tsx
- src/frontend/src/primitives/Spinner.tsx
Allow passing custom spinner size.
Needed to align the spinner height with an inline button.
> ♻️(frontend) parametrize spinner size

- src/backend/locale/en_US/LC_MESSAGES/django.po
- src/backend/locale/fr_FR/LC_MESSAGES/django.po
Regenerate translation files to include all recent backend string changes. Address backlog of untranslated content that accumulated during recent development cycles.
> 🌐(backend) generate missing translations for backend updates

- src/frontend/src/features/sdk/routes/CreateMeetingButton.tsx
- src/frontend/src/locales/fr/sdk.json
Minor enhancement on the calendar integration
It closes #463
> Minor enhancement on the calendar integration

- src/backend/core/recording/event/notification.py
- src/backend/core/recording/worker/services.py
- src/backend/core/tests/recording/event/test_notification.py
- src/frontend/src/features/recording/components/RecordingStateToast.tsx
- src/frontend/src/features/recording/components/ScreenRecordingSidePanel.tsx
- src/frontend/src/features/recording/components/TranscriptSidePanel.tsx
- src/frontend/src/features/recording/hooks/useIsRecordingActive.ts
- src/frontend/src/features/recording/index.ts
- src/frontend/src/features/rooms/livekit/components/Tools.tsx
- src/frontend/src/locales/en/rooms.json
- src/frontend/src/locales/fr/rooms.json
- src/frontend/src/locales/nl/rooms.json
- src/frontend/src/primitives/Spinner.tsx
Based on user feedbacks and intuition, enhance Recording UX.
Minor interface changes.
> Enhance UX recording

- src/backend/core/api/serializers.py
- src/backend/core/tests/recording/test_api_recordings_list.py
- src/backend/core/tests/recording/test_api_recordings_retrieve.py
- src/frontend/src/api/mediaUrl.ts
- src/frontend/src/features/recording/api/fetchRecording.ts
- src/frontend/src/features/recording/index.ts
- src/frontend/src/features/recording/routes/RecordingDownload.tsx
- src/frontend/src/features/recording/types.ts
- src/frontend/src/locales/de/recording.json
- src/frontend/src/locales/en/recording.json
- src/frontend/src/locales/fr/recording.json
- src/frontend/src/locales/nl/recording.json
- src/frontend/src/routes.ts
- src/frontend/src/utils/formatDate.ts
Allow download a recording from the frontend interface.
Link will be received by email.
> Download recording

- src/helm/meet/Chart.yaml
Bump chart version to publish a new one with media related logic (ingress, service, etc…)
> 🔐(helm) bump chart version

- src/backend/pyproject.toml
- src/frontend/package-lock.json
- src/frontend/package.json
- src/mail/package-lock.json
- src/mail/package.json
- src/sdk/library/package.json
- src/sdk/package-lock.json
- src/sdk/package.json
- src/summary/pyproject.toml
> 🔖(minor) bump release to 0.1.19

- src/backend/meet/settings.py
- src/frontend/src/api/useConfig.ts
- src/frontend/src/components/FeedbackBanner.tsx
- src/frontend/src/features/rooms/components/Rating.tsx
- src/frontend/src/features/rooms/livekit/components/controls/Options/FeedbackMenuItem.tsx
- src/frontend/src/features/rooms/livekit/prefabs/ControlBar/MobileControlBar.tsx
- src/frontend/src/locales/en/global.json
- src/frontend/src/locales/fr/global.json
- src/frontend/src/locales/nl/global.json
- src/frontend/src/utils/constants.ts
- src/helm/env.d/dev-keycloak/values.meet.yaml.gotmpl
> Self-hosting: customization of feedbacks elements

- src/frontend/src/features/rooms/livekit/components/controls/ReactionsToggle.tsx
- src/frontend/src/hooks/useRateLimiter.ts
Avoid DoS when someone sends a Reaction !
> Rate limit reactions

- src/backend/pyproject.toml
- src/frontend/package-lock.json
- src/frontend/package.json
- src/mail/package-lock.json
- src/mail/package.json
- src/sdk/library/package.json
- src/sdk/package-lock.json
- src/summary/pyproject.toml
> 🔖(minor) bump release to 0.1.20

- src/backend/pyproject.toml
- src/frontend/package-lock.json
- src/frontend/package.json
- src/mail/package-lock.json
- src/mail/package.json
- src/sdk/library/package.json
- src/sdk/package-lock.json
- src/sdk/package.json
- src/summary/pyproject.toml
Refactor authentication.
Address few bug bounties.
> 🔖(minor) bump release to 0.1.21

- README.md
So that community members can gather and chat about meet
> 📝(readme) add matrix room to readme

- src/backend/pyproject.toml
- src/frontend/package-lock.json
- src/frontend/package.json
- src/mail/package-lock.json
- src/mail/package.json
- src/sdk/library/package.json
- src/sdk/package-lock.json
- src/sdk/package.json
- src/summary/pyproject.toml
Upgrade track processor to benefits from webgl.
> 🔖(minor) bump release to 0.1.22

- src/frontend/src/features/rooms/index.ts
- src/frontend/src/features/rooms/routes/Room.tsx
- src/frontend/src/features/rooms/utils/isRoomValid.ts
- src/frontend/src/routes.ts
Enhance meeting code input to accept codes without hyphens and make input case-insensitive. Addresses usability issue observed with touch screen and virtual keyboard users who struggled with precise formatting. Improves accessibility for users with pointing pens and limited input precision.
requested by @spaccoud
it closes #518
> ✨(frontend) improve meeting code input accessibility for touch devices

- bin/Tiltfile
Fix the cp permission issue for linux users
> ⚡️(tilt) fix cp for linux users

- src/backend/meet/settings.py
We want to be able to increase the duration of the cookie session by setting an environment variable.
> ✨(backend) allow setting session cookie age via env var

- src/frontend/src/locales/fr/rooms.json
Update French translation of effects feature based on user feedback to better reflect its purpose as background effects rather than generic effects.
It closes #542
> 🌐(frontend) rename "appliquer des effets" to "effets d'arrière plan"

- src/frontend/Dockerfile
Cyberwatch reported security issues with the frontend Docker image.
> 🔒️(front) improve docker image security

- src/frontend/src/features/notifications/NotificationDuration.ts
- src/frontend/src/features/notifications/NotificationType.ts
- src/frontend/src/features/notifications/components/ToastProvider.tsx
- src/frontend/src/features/notifications/components/ToastRecordingSaving.tsx
- src/frontend/src/features/notifications/components/ToastRegion.tsx
- src/frontend/src/features/notifications/index.ts
- src/frontend/src/features/notifications/utils.ts
- src/frontend/src/features/recording/components/RecordingStateToast.tsx
- src/frontend/src/features/recording/components/ScreenRecordingSidePanel.tsx
- src/frontend/src/features/recording/components/TranscriptSidePanel.tsx
- src/frontend/src/features/recording/hooks/useHasFeatureWithoutAdminRights.ts
- src/frontend/src/features/recording/index.ts
- src/frontend/src/locales/de/notifications.json
- src/frontend/src/locales/de/rooms.json
- src/frontend/src/locales/en/notifications.json
- src/frontend/src/locales/en/rooms.json
- src/frontend/src/locales/fr/notifications.json
- src/frontend/src/locales/fr/rooms.json
- src/frontend/src/locales/nl/notifications.json
- src/frontend/src/locales/nl/rooms.json
- src/summary/summary/core/celery_worker.py
> Enhance transcript UX

- src/backend/pyproject.toml
- src/frontend/package-lock.json
- src/frontend/package.json
- src/mail/package-lock.json
- src/mail/package.json
- src/sdk/package-lock.json
- src/sdk/package.json
- src/summary/pyproject.toml
> 🔖(minor) bump release to 0.1.23

- src/frontend/package-lock.json
- src/frontend/package.json
- src/frontend/src/features/rooms/livekit/prefabs/Chat.tsx
> Fix screen share

- src/frontend/src/features/rooms/components/Conference.tsx
- src/frontend/src/features/rooms/components/Join.tsx
- src/frontend/src/features/rooms/livekit/components/controls/SelectToggleDevice.tsx
- src/frontend/src/features/rooms/livekit/hooks/usePersistentUserChoices.ts
- src/frontend/src/features/rooms/livekit/prefabs/ControlBar/ControlBar.tsx
- src/frontend/src/features/rooms/routes/Room.tsx
- src/frontend/src/features/settings/components/tabs/AudioTab.tsx
- src/frontend/src/locales/de/settings.json
- src/frontend/src/locales/en/settings.json
- src/frontend/src/locales/fr/settings.json
- src/frontend/src/locales/nl/settings.json
- src/frontend/src/stores/userChoices.ts
Description...
Description...
- [] item 1...
- [] item 2...
> Refacto userchoices

- src/backend/pyproject.toml
- src/frontend/package-lock.json
- src/frontend/package.json
- src/mail/package-lock.json
- src/mail/package.json
- src/sdk/package-lock.json
- src/sdk/package.json
- src/summary/pyproject.toml
Fix chat issue livekit/components-js#1173
Bump backend dependencies
Switch to python v13
> 🔖(minor) bump release to 0.1.25

- src/frontend/package-lock.json
- src/frontend/package.json
- src/frontend/src/features/analytics/enums.ts
- src/frontend/src/features/rooms/livekit/hooks/useNoiseReduction.ts
- src/frontend/src/features/rooms/livekit/hooks/useNoiseReductionAvailable.ts
- src/frontend/src/features/rooms/livekit/hooks/usePersistentUserChoices.ts
- src/frontend/src/features/rooms/livekit/prefabs/VideoConference.tsx
- src/frontend/src/features/rooms/livekit/processors/RnnNoiseProcessor.ts
- src/frontend/src/features/settings/components/tabs/AudioTab.tsx
- src/frontend/src/locales/de/settings.json
- src/frontend/src/locales/en/settings.json
- src/frontend/src/locales/fr/settings.json
- src/frontend/src/locales/nl/settings.json
- src/frontend/src/stores/userChoices.ts
Description...
Description...
- [] item 1...
- [] item 2...
> support rnn suppression

- src/backend/pyproject.toml
- src/frontend/package-lock.json
- src/frontend/package.json
- src/mail/package-lock.json
- src/mail/package.json
- src/sdk/package-lock.json
- src/sdk/package.json
- src/summary/pyproject.toml
Add noise reduction with RNNoise.
New feature needs to be battle tested,
it's protected with a feature flag.
> 🔖(minor) bump release to 0.1.26

- src/backend/meet/settings.py
Defaulting to false for now to keep compatibility.
PKCE is good and everyone should use it.
Use PKCE.
> Add environment variable for PKCE setting

- src/backend/pyproject.toml
- src/frontend/package-lock.json
- src/frontend/package.json
- src/mail/package-lock.json
- src/mail/package.json
- src/sdk/package-lock.json
- src/sdk/package.json
- src/summary/pyproject.toml
What:
- fix minor issue on summary microservice
- PKCE (oidc) support
- add limitation on recording if supported
and more.
> 🔖(minor) bump release to 0.1.29

- src/backend/pyproject.toml
- src/frontend/package-lock.json
- src/frontend/package.json
- src/mail/package-lock.json
- src/mail/package.json
- src/sdk/package-lock.json
- src/sdk/package.json
- src/summary/pyproject.toml
Fix noise reduction feature flag
> 🔖(minor) bump release to 0.1.31

- src/backend/pyproject.toml
- src/frontend/package-lock.json
- src/frontend/package.json
- src/mail/package-lock.json
- src/mail/package.json
- src/sdk/package-lock.json
- src/sdk/package.json
- src/summary/pyproject.toml
> 🔖(minor) bump release to 0.1.32

- src/backend/core/api/__init__.py
- src/backend/meet/settings.py
- src/frontend/src/api/useConfig.ts
- src/frontend/src/features/rooms/components/Conference.tsx
- src/helm/env.d/dev-keycloak/values.meet.yaml.gotmpl
Description...
Description...
- [] item 1...
- [] item 2...
>  fix connection warmup with WebSocket pre-authentication

- src/backend/pyproject.toml
- src/frontend/package-lock.json
- src/frontend/package.json
- src/mail/package-lock.json
- src/mail/package.json
- src/sdk/package-lock.json
- src/sdk/package.json
- src/summary/pyproject.toml
Warmup with WebSocket pre-authentication on FF
> 🔖(minor) bump release to 0.1.33

- src/frontend/src/features/home/components/LaterMeetingDialog.tsx
- src/frontend/src/features/home/routes/Home.tsx
- src/frontend/src/features/rooms/components/Conference.tsx
- src/frontend/src/features/rooms/components/InviteDialog.tsx
- src/frontend/src/features/rooms/livekit/components/Info.tsx
- src/frontend/src/features/rooms/livekit/hooks/useCopyRoomToClipboard.ts
- src/frontend/src/features/rooms/utils/telephony.ts
- src/frontend/src/locales/de/global.json
- src/frontend/src/locales/de/home.json
- src/frontend/src/locales/de/rooms.json
- src/frontend/src/locales/en/global.json
- src/frontend/src/locales/en/home.json
- src/frontend/src/locales/en/rooms.json
- src/frontend/src/locales/fr/global.json
- src/frontend/src/locales/fr/home.json
- src/frontend/src/locales/fr/rooms.json
- src/frontend/src/locales/nl/global.json
- src/frontend/src/locales/nl/home.json
- src/frontend/src/locales/nl/rooms.json
- src/frontend/src/primitives/buttonRecipe.ts
- src/helm/env.d/dev-keycloak/values.meet.yaml.gotmpl
> Display phone numbers across the app

- src/frontend/src/features/rooms/components/Join.tsx
- src/frontend/src/features/rooms/components/join/SelectDevice.tsx
- src/frontend/src/features/rooms/components/join/ToggleDevice.tsx
- src/frontend/src/features/rooms/livekit/components/controls/SelectToggleDevice.tsx
- src/frontend/src/features/rooms/livekit/components/controls/ToggleDevice.tsx
- src/frontend/src/features/rooms/livekit/config/ToggleDeviceConfig.ts
- src/frontend/src/features/rooms/livekit/hooks/useResolveDefaultDevice.ts
- src/frontend/src/locales/de/rooms.json
- src/frontend/src/locales/en/rooms.json
- src/frontend/src/locales/fr/rooms.json
- src/frontend/src/locales/nl/rooms.json
- src/frontend/src/primitives/buttonRecipe.ts
Prepare the addition of the speaker selector.
> Rework prejoin UX

- src/frontend/src/features/rooms/components/Conference.tsx
- src/frontend/src/features/rooms/livekit/hooks/usePersistentUserChoices.ts
- src/frontend/src/features/rooms/livekit/hooks/useVideoResolutionSubscription.ts
- src/frontend/src/features/rooms/livekit/prefabs/VideoConference.tsx
- src/frontend/src/features/settings/components/SettingsDialogExtended.tsx
- src/frontend/src/features/settings/components/tabs/AudioTab.tsx
- src/frontend/src/features/settings/components/tabs/VideoTab.tsx
- src/frontend/src/features/settings/components/tabs/layout/RowWrapper.tsx
- src/frontend/src/locales/de/settings.json
- src/frontend/src/locales/en/settings.json
- src/frontend/src/locales/fr/settings.json
- src/frontend/src/locales/nl/settings.json
- src/frontend/src/stores/userChoices.ts
Allow user configure their video
> Add a video settings tab

- src/frontend/src/features/rooms/components/Conference.tsx
Revert recent changes to dynacast and adaptive streaming functionality to isolate potential causes of regression issues. Changes will be reintroduced in future commits, with improved error handling and thorough investigation of root causes.
> ⏪️(frontend) revert dynacast and adaptive streaming checks

- src/frontend/package-lock.json
- src/frontend/package.json
- src/frontend/src/features/rooms/components/Join.tsx
- src/frontend/src/features/rooms/components/Permissions.tsx
- src/frontend/src/features/rooms/livekit/components/controls/Device/PermissionNeededButton.tsx
- src/frontend/src/features/rooms/livekit/components/controls/Device/ToggleDevice.tsx
- src/frontend/src/features/rooms/livekit/components/controls/Participants/ParticipantListItem.tsx
- src/frontend/src/stores/permissions.ts
> Bump livekit deps

- src/agents/pyproject.toml
- src/backend/pyproject.toml
- src/frontend/package-lock.json
- src/frontend/package.json
- src/mail/package-lock.json
- src/mail/package.json
- src/sdk/package-lock.json
- src/sdk/package.json
- src/summary/pyproject.toml
- bump LiveKit dependencies
- fix some regressions link to permissions
> 🔖(minor) bump release to 0.1.38
