- env.d/development/common.dist
- src/backend/core/api/serializers.py
- src/backend/core/api/viewsets.py
- src/backend/core/tests/rooms/test_api_rooms_retrieve.py
- src/backend/meet/settings.py
- src/frontend/.env.development
- src/frontend/.eslintrc.cjs
- src/frontend/src/api/ApiRoom.ts
- src/frontend/src/api/apiUrl.ts
- src/frontend/src/routes/Conference.tsx
- src/frontend/src/vite-env.d.ts
- src/helm/env.d/dev/values.meet.yaml.gotmpl
- src/helm/env.d/preprod/secrets.enc.yaml
- src/helm/env.d/preprod/values.meet.yaml.gotmpl
- src/helm/env.d/production/secrets.enc.yaml
- src/helm/env.d/production/values.meet.yaml.gotmpl
- src/helm/env.d/staging/secrets.enc.yaml
- src/helm/env.d/staging/values.meet.yaml.gotmpl
- src/helm/extra/templates/secrets.yaml
Prepare deployment in staging, and production.
Setting up the CI/CD as soon as possible is crucial for iteration. It's also essential to start getting user feedback next week. Therefore, having an MVP in users' hands is a must.
A pre-production environment can be prepared, but it won't be useful for the MVP. The pre-production environment will be necessary once we can no longer afford to risk breaking the production environment. Early user testers will be aware that the product is in beta version.
Deploying a first version based on Indie Hoster and Google infrastructure is okay for the early user testers. We cannot block deployment until @rouja deployed an enhanced and totally sovereign version of LiveKit.
Deploying LiveKit on a Kubernetes cluster managed by private cloud providers is …
> Prepare deployment

- .github/workflows/meet.yml
- src/frontend/default.conf
It closes #24 
I have added some caching on static assets, lmk @manuhabitela wdyt about it.
> Fix: Error 404 in staging

- .gitignore
- README.md
- docker-compose.yml
- docker/livekit/config/livekit-egress.yaml
- docker/livekit/config/livekit-server.yaml
- docker/livekit/egress-example/room-composite-file.json
- docs/egress.md
- env.d/development/common.dist
Run locally the Egress service.
Necessary for the issue #12.
I have cleaned the closed PR #13, which was a draft.
Everything is explained in commits' body.
> Add LiveKit Egress service

- src/frontend/src/features/auth/api/fetchUser.ts
- src/frontend/src/features/auth/index.ts
- src/frontend/src/features/auth/utils/logoutUrl.ts
- src/frontend/src/layout/Header.tsx
- src/frontend/src/routes/Home.tsx
Minor changes.
Nothing special, only nit-picking / refactoring.
> Frontend adjustements

- docs/release.md
Heavily inspired from openfun handbook instructions, https://handbook.openfun.fr/git
Document how to release a new version. Might be a common documentation shared with Impress, Regie and Meet projects. Let's discuss it.
It's quite important that anyone should know how to release, as we plan to release every week an enhanced version.
> 📝(release) document releasing new version

- src/helm/env.d/preprod/values.meet.yaml.gotmpl
- src/helm/env.d/production/values.meet.yaml.gotmpl
- src/helm/env.d/staging/values.meet.yaml.gotmpl
Change configuration to use livekit-preprod.beta.numerique.gouv.fr instead of the docker test vm
> 🔧(helm) configuration

- src/frontend/src/App.tsx
- src/frontend/src/features/rooms/index.ts
- src/frontend/src/features/rooms/utils/generateRoomId.ts
Simplify room's name (ID).
Please refer to the issue #41 which explains why simplifying room IDs could be beneficial in terms of user experience (UX).
It closes #41.
> 🚸(frontend) generate shorter room IDs making URLs easier to share

- src/frontend/i18next-parser.config.json
- src/frontend/src/locales/de/global.json
- src/frontend/src/locales/de/home.json
- src/frontend/src/locales/en/global.json
- src/frontend/src/locales/en/home.json
- src/frontend/src/locales/fr/global.json
- src/frontend/src/locales/fr/home.json
when adding keys by hand, we didn't really know where to add them so that the i18n:extract command would not move them afterwards. Feels like this will help.
I guess a CI thing checking if the locales file dont change after a push would be helpful
> 🌐(frontend) sort extrated locales to help prevent conflicts

- src/frontend/src/features/rooms/components/Conference.tsx
- src/frontend/src/features/rooms/routes/Room.tsx
Following antoine's comment: https://github.com/numerique-gouv/meet/pull/42#issuecomment-2237118265
Makes more sense that way: only the Room _route_ knows about route params, not the internal component used.
> ️♻️(frontend) make the Conference component not know about routing

- src/backend/core/api/serializers.py
- src/backend/core/api/viewsets.py
- src/backend/core/tests/rooms/test_api_rooms_retrieve.py
- src/backend/core/utils.py
Display the username typed by user.
The frontend was ready. I've added a new query parameter `username` to the `/room` route in the API. We moved away from email/UUID-v4 usernames, which were totally ugly.
I haven't thoroughly tested all corner cases when passing the string yet. Also, the `generate_token` function lacks unit tests; I will address this asap.
If we're not planning to use named/persistent rooms soon, I propose extracting the LiveKit token generation into a dedicated endpoint. We could take inspiration from the LiveKit demo app, like `https://meet.livekit.io/api/token?identity=Antoine&name=Antoine&roomName=guj4-212l`.
I'm concerned about updating code that might not be used. Before adding complexity to the existing viewset and serializer, I'd prefer to ensure we're heading in …
> Handle username in the API

- src/frontend/src/layout/Header.tsx
- src/frontend/src/locales/de/rooms.json
- src/frontend/src/locales/en/rooms.json
- src/frontend/src/locales/fr/rooms.json
- src/frontend/src/utils/useMatchesRoute.ts
now clicking on the header homepage link asks for confirmation when on the route page.
this is quick and dirty, using browser confirm ui, and not making a difference between join page and conference page, but it'll do for now
> 🚸(room) prevent user from misclicking out of a meeting

- .github/workflows/deploy.yml
- .github/workflows/docker-hub.yml
- .github/workflows/meet.yml
It closes #60 
checkout@v2 uses `node12` which will be deprecated soon. I've aligned CI configurations to use a more recent action, already in-use in the 'meet.yml' flow.
> ⬆️(ci) update checkout actions

- .github/workflows/meet.yml
- env.d/development/common.dist
Minio was removed from our stack, because it wasn't used.
Cleaned up some environment variables.
> ⚰️(backend) remove unused cold storage configurations

- src/frontend/src/features/rooms/components/Conference.tsx
It closes #50 
Adopted LiveKit demo app approach for passing configuration to `LiveKitRoom`. Introduced `roomOptions` for future customizations (e.g., quality, codec).
DeviceId is persisted in local storage despite the boolean flag.
We ended up passing the DeviceId without ever setting the boolean flag to false when any parameter was disabled.
I might have missed smth, please feel free to add any commits.
> 🩹(frontend) fix ignored pre-join options

- README.md
Based on @rouja instructions, try to document the Tilt stack, to enhance the DX of any newcomers, discovering Meet and trying to run it on K8s.
Having a shared/common onboarding documentation on Tilt with Impress, Regie, and Meet would be amazing.
Especially, to document how to install Tilt and its dependencies.
Important: The frontend is not deployed locally using the production target, and I feel important to document it.
> 📝(tilt) document running the application with Tilt

- src/backend/core/tests/rooms/test_api_rooms_retrieve.py
Django Rest Framework (DRF) recent updates broke one unit test, that was checking for a default error message returned by DRF. Updated the message.
> ✅(backend) fix test broken by dependencies update

- src/frontend/src/i18n/useLanguageLabels.ts
- src/frontend/src/layout/Header.tsx
- src/frontend/src/primitives/PopoverList.tsx
Fix warnings on the popoverlist component.
Close #91 
Please check commits for more information.
> Fix minor warnings on the PopoverList component

- docs/release.md
I added an example in the documentation to ensure we remember to upgrade the frontend image during the release process. This will help prevent any issues related to outdated images when deploying new versions.
(I did this mistake while releasing)
> 📝(doc) add an example for the frontend image

- src/frontend/src/primitives/Select.tsx
- src/frontend/src/primitives/menuItemRecipe.ts
Extra padding should be reserved for select options that display a checkmark when an option is selected.
> 💄(frontend) reserve left padding for select options

- src/backend/meet/settings.py
Upgrading Django to 5.1 created a severe issue.
Migrate and create-superuser jobs were failing.
The issue originated from the third party `easy_thumbnail`. Please refer to the issue #641 on their repo.
This is the suggested workaround by @Miketsukami.
> 🐛(backend) fix dependencies conflicts

- src/frontend/src/features/rooms/components/InviteDialog.tsx
- src/frontend/src/locales/de/rooms.json
- src/frontend/src/locales/en/rooms.json
- src/frontend/src/locales/fr/rooms.json
Enhance user experience when creating a room.
Avoid friction when joining the room. Nothing should block you from starting the meeting immediately. The overlay required an extra interaction to close it before starting the meeting.
> Invitation Dialog V2

- src/frontend/src/components/SoundTester.tsx
- src/frontend/src/features/settings/components/SettingsDialogExtended.tsx
- src/frontend/src/features/settings/components/tabs/AudioTab.tsx
- src/frontend/src/primitives/Dialog.tsx
- src/frontend/src/primitives/Field.tsx
- src/frontend/src/primitives/Select.tsx
Second iteration on the Audio tab under settings
Added the active speaker indicator to help users easily determine if their mic is active. Refactored the layout to match Gmeet's design and improved the responsiveness of several elements.
> Setting dialog audio v2

- src/frontend/panda.config.ts
- src/frontend/src/features/rooms/livekit/api/lowerHandParticipant.ts
- src/frontend/src/features/rooms/livekit/api/lowerHandParticipants.ts
- src/frontend/src/features/rooms/livekit/components/ParticipantTile.tsx
- src/frontend/src/features/rooms/livekit/components/controls/HandToggle.tsx
- src/frontend/src/features/rooms/livekit/components/controls/Participants/HandRaisedListItem.tsx
- src/frontend/src/features/rooms/livekit/components/controls/Participants/ListItemActionButton.tsx
- src/frontend/src/features/rooms/livekit/components/controls/Participants/LowerAllHandsButton.tsx
- src/frontend/src/features/rooms/livekit/components/controls/Participants/ParticipantListItem.tsx
- src/frontend/src/features/rooms/livekit/components/controls/Participants/ParticipantsCollapsableList.tsx
- src/frontend/src/features/rooms/livekit/components/controls/Participants/ParticipantsList.tsx
- src/frontend/src/features/rooms/livekit/hooks/useRaisedHand.tsx
- src/frontend/src/features/rooms/livekit/prefabs/ControlBar.tsx
- src/frontend/src/locales/de/rooms.json
- src/frontend/src/locales/en/rooms.json
- src/frontend/src/locales/fr/rooms.json
- src/frontend/src/primitives/buttonRecipe.ts
Allow users to raise their hands.
It closes #122 
A new toggle has been added to the control bar:
https://github.com/user-attachments/assets/c85d3f35-43df-4577-b459-2b3be9ab5b36
When a participant raised her hand, a new indicator appears on the left-side of its name:
https://github.com/user-attachments/assets/2a6a1058-5e40-4cd5-8241-fa951c75f969
Also, inspired by Gmeet, a waiting room has been added to the participant menu:
https://github.com/user-attachments/assets/e2cdfb7b-1a0c-41c4-84ca-c136efdae629
> Raise hand V1

- src/backend/core/utils.py
hash built-in function is randomly seed by Python process. In staging or production, our backend runs over 3 pods, thus 3 Python processes. For a given identity, it was not prompting the same hash across all pods.
> 🩹(backend) fix identity hash randomness

- src/frontend/src/features/auth/api/useUser.tsx
Oupsie… quotes were misplaced, and led to having the exact same ID for every user. Fixed them. Trivial error.
> 🚑️(frontend) fix posthog user's ID

- src/frontend/package-lock.json
- src/frontend/package.json
Upgraded to livekit/components-react v2.5.4, fixing a bug in v2.5.3 that caused repeated nesting of persistent user choices, exhausting the quota. Thanks to Lukas for the quick fix.
> ⬆️(frontend) fix persistent choices nesting issue

- src/helm/meet/templates/secrets.yaml
When new secret is added to backend secret, it's not sync at the beginning of argocd synchronisation and jobs are blocked. Theses new annotations fix this issue.
> 🔒️(helm) fix secret sync precedence

- src/frontend/src/features/rooms/livekit/components/controls/Options/OptionsMenuItems.tsx
Tchap is no longer relevant due to the integration of Crisp. The Tchap channel will be deleted.
> ♻️(frontend) remove Tchap support

- src/frontend/src/features/rooms/livekit/hooks/useWidgetInteraction.ts
Fixed issue where side panel could open while chat was already open. Resolved recent bug introduced in a previous commit.
> 🐛(frontend) prevent side panel and chat from opening simultaneously

- src/backend/meet/settings.py
Fix following warning messages :
```
You have not set a value for the SECURE_HSTS_SECONDS setting.
Your SECURE_SSL_REDIRECT setting is not set to True.
```
> 🔧(backend) fix configuration to avoid different ssl warning

- src/frontend/src/features/rooms/components/Join.tsx
- src/frontend/src/locales/de/rooms.json
- src/frontend/src/locales/en/rooms.json
- src/frontend/src/locales/fr/rooms.json
Add missing hint to guide user entering their name while joining a room.
> 🐛(frontend) fix missing user label in prejoin screen

- src/frontend/src/features/rooms/components/Conference.tsx
Context: DINUM users face connection issues in bandwidth-constrained environments. They cannot reach their room, the peer connection timeouts while negotiating TURN/TLS handshake (from our current understanding).
I am not sure this issue is linked to those parameters, at least try something.
> 🐛(frontend) tune connection parameters for low bandwidth clients

- src/frontend/src/i18n/init.ts
Previously, language detection was failing to read browser settings correctly. Added explicit detection order to ensure  localStorage preferences are checked before falling back to browser language.
> 🩹(frontend) use browser language if no localStorage for detection

- src/helm/extra/templates/s3.yaml
Wrong copy and paste. My bad, bucket's name wasn't matching our project.
> 🐛(helm) rename bucket

- src/backend/core/recording/event/authentication.py
- src/backend/meet/settings.py
- src/frontend/src/api/useConfig.ts
- src/frontend/src/features/rooms/api/ApiRoom.ts
- src/frontend/src/features/rooms/api/startRecording.ts
- src/frontend/src/features/rooms/api/stopRecording.ts
- src/frontend/src/features/rooms/livekit/components/controls/Options/OptionsMenuItems.tsx
- src/frontend/src/features/rooms/livekit/components/controls/Options/TranscriptMenuItem.tsx
- src/frontend/src/features/rooms/livekit/prefabs/ControlBar.tsx
- src/frontend/src/locales/de/rooms.json
- src/frontend/src/locales/en/rooms.json
- src/frontend/src/locales/fr/rooms.json
- src/helm/env.d/dev/values.meet.yaml.gotmpl
- src/helm/env.d/staging/values.meet.yaml.gotmpl
- src/helm/meet/templates/secrets.yaml
The recording feature needs to be enabled in the dev and staging environments. 
Currently, the MinIO webhook is broken. When using the nip.io address, while the MinIO post the webhook, it results in certificate errors, preventing MinIO from posting to the webhook ofc. 
I've tried to read MinIO config documentation. Other type of notification seems to offer a `skip_ssl_verification` which is not supported for the webhook type.
My goal is to add a bucket event notification on `Put` on our bucket. I would like to configure everything in the helmfile, so any dev starting the project has no configuration to do.
> Enable recording

- src/frontend/src/App.tsx
- src/frontend/src/features/rooms/livekit/components/controls/SupportToggle.tsx
- src/frontend/src/features/rooms/livekit/prefabs/ControlBar.tsx
- src/frontend/src/locales/de/rooms.json
- src/frontend/src/locales/en/rooms.json
- src/frontend/src/locales/fr/rooms.json
- src/frontend/src/styles/index.css
We want the bottom bar to stay at the center of the screen + I also added a bit of vertical spacing around the control bar @lebaudantoine .
> 📱(front) improve control bar responsive

- src/helm/env.d/dev/values.meet.yaml.gotmpl
- src/helm/env.d/staging/values.meet.yaml.gotmpl
- src/summary/summary/core/celery_worker.py
Switch from OpenAI to our own self-hosted models.
> Use our self-deployed models

- src/backend/meet/settings.py
`sentry_sdk.configure_scope` is deprecated and will be removed in the next major version.
(commit taken from people by @qbey)
> 🔧(backend) fix sentry deprecated scope

- src/frontend/src/features/rooms/components/Conference.tsx
Address #237 and in general optimize bandwidth usage for large room. 
I've enabled several key optimizations from LiveKit, including Adaptive Stream, Dynacast, and modern video codecs. I’m not sure why we didn’t enable these earlier—my mistake.
I spent a significant amount of time reviewing LiveKit’s code, exploring other projects that use it, viewing conferences, and reading the official WebRTC documentation. Based on that, I believe the changes in my commit are optimal.
Locally, I tested it by creating a room and joining with Chrome on one side and Firefox on the other. VP9 decoding works on Firefox, while the Firefox client sends VP8.
Using `about:webrtc`, I confirmed that Dynacast and Adaptive Stream were enabled. For example, when the other participant is on a different tab, my video …
> Optimizations

- src/frontend/src/components/FeedbackBanner.tsx
- src/frontend/src/features/rooms/livekit/components/controls/Options/OptionsMenuItems.tsx
- src/frontend/src/utils/constants.ts
It led to an error, with two occurrences of the form's URL being desynchronized. Fix this minor issue, and refactor the constant in a constant file to be shared across the app.
> 🩹(frontend) avoid duplicating Grist form's URL

- src/backend/core/models.py
- src/backend/core/tests/test_api_users.py
Found this solution googling on Stack Overflow.
Without a default ordering on a model, Django raises a warning, that pagination may yield inconsistent results.
> 🚨(backend) fix Django UnorderedObjectListWarning on User and ResourceAccess

- src/backend/core/authentication/backends.py
- src/backend/core/services/marketing_service.py
- src/backend/core/tests/authentication/test_backends.py
- src/backend/core/tests/services/test_marketing_service.py
- src/backend/meet/settings.py
- src/backend/pyproject.toml
Create the infrastructure for Marketing automation with our first users.
Please check my commits;
> POC a Brevo integration

- .github/workflows/release-helm-chart.yaml
Fix the following issue :
```
The workflow is not valid. .github/workflows/release-helmchart.yml
(Line: 25, Col: 12): Job 'release' depends on unknown job
'helmfile-lint'.
```
> 👷(helm) fix typo in the ci

- src/backend/meet/settings.py
- src/helm/env.d/dev/values.meet.yaml.gotmpl
Using VaultWarden, added a dev Brevo API key.
In the "dev" stack, enable Brevo to validate new users are signed-up to the marketing emails.
Can be merged after #299
> 🔐(helm) configure Brevo marketing tool

- src/frontend/package-lock.json
- src/frontend/package.json
Updates build configuration to support new major version. This might introduce some breaking changes.
I've read their migration guide, everything seems okay.
Could you double-check https://vite.dev/guide/migration.html @NathanVss?
> ⬆️(frontend) bump vite to v6.0.7

- src/frontend/src/features/rooms/livekit/components/controls/CameraSwitchButton.tsx
- src/frontend/src/features/rooms/livekit/components/controls/SelectToggleDevice.tsx
- src/frontend/src/features/rooms/livekit/components/controls/ToggleDevice.tsx
- src/frontend/src/features/rooms/livekit/prefabs/ControlBar/MobileControlBar.tsx
- src/frontend/src/locales/de/rooms.json
- src/frontend/src/locales/en/rooms.json
- src/frontend/src/locales/fr/rooms.json
- Add switch camera button
- Remove chevron from toggle switches
> (front) add switch camera on mobile

- src/frontend/src/features/rooms/components/Join.tsx
- src/frontend/src/features/rooms/livekit/components/controls/SelectToggleDevice.tsx
- src/frontend/src/features/rooms/livekit/components/controls/ToggleDevice.tsx
- src/frontend/src/features/rooms/livekit/prefabs/ControlBar/DesktopControlBar.tsx
- src/frontend/src/locales/de/rooms.json
- src/frontend/src/locales/en/rooms.json
- src/frontend/src/locales/fr/rooms.json
- src/frontend/src/primitives/Field.tsx
The previous prejoin screenshot was misleading for some screen size, for small screen the join button was invisible + we want to align with the most up to date styles we use.
https://github.com/user-attachments/assets/0b5aae8c-dd83-414a-94ad-94e3b0e6cc2b
> ✨(front) revamp pre join screen

- src/frontend/src/features/rooms/livekit/components/controls/TranscriptToggle.tsx
- src/frontend/src/features/rooms/livekit/prefabs/ControlBar/DesktopControlBar.tsx
- src/frontend/src/features/rooms/livekit/prefabs/ControlBar/MoreOptions.tsx
- src/frontend/src/locales/de/rooms.json
- src/frontend/src/locales/en/rooms.json
- src/frontend/src/locales/fr/rooms.json
- src/frontend/src/primitives/buttonRecipe.ts
Implemented collapsible advanced options to maintain usability on narrow screens following GMeet's UX pattern. Dialog and popover components were chosen based on GMeet choices, though this introduces potential accessibility concerns that should be addressed in future iterations.
Current implementation uses JS for breakpoint handling due to challenges with Panda CSS's pure CSS approach. This workaround was necessary to resolve a persistent issue where the popover remained open after window expansion beyond 750px, even after the lateral menu trigger was removed from view.
Technical debt note: Code needs refinement, particularly around breakpoint management and component architecture. (Prioritized shipping over perfection to meet immediate responsive design needs)
> 📱 (frontend) enhance control bar responsiveness for better UX

- src/frontend/vite.config.ts
I recently got the error:
> Blocked request. This host ("meet.127.0.0.1.nip.io") is not allowed.
> To allow this host, add "meet.127.0.0.1.nip.io" to server.allowedHosts in vite.config.js.
We apparently need to explicitly allow these domains in Vite's server configuration to prevent host security violations.
This check should be ignored when using HTTPS.
I've made local config changes that might create this issue. @NathanVss, can you reproduce?
> 🩹(frontend) fix allowed hosts by Vite using the Tilt stack

- src/frontend/src/features/rooms/livekit/components/controls/Options/EffectsMenuItem.tsx
- src/frontend/src/features/rooms/livekit/components/controls/Options/FeedbackMenuItem.tsx
- src/frontend/src/features/rooms/livekit/components/controls/Options/FullScreenMenuItem.tsx
- src/frontend/src/features/rooms/livekit/components/controls/Options/OptionsMenuItems.tsx
- src/frontend/src/features/rooms/livekit/components/controls/Options/SettingsMenuItem.tsx
- src/frontend/src/features/rooms/livekit/hooks/useFullScreen.ts
- src/frontend/src/locales/de/rooms.json
- src/frontend/src/locales/en/rooms.json
- src/frontend/src/locales/fr/rooms.json
Added an option allowing users to trigger the fullscreen mode while on desktop. Heavily inspired by the PR #279 from @sylvinus.
Yet, this option allow user to enable/disable the fullscreen mode on the whole ui, in the next iteration I'll add the same feature but for a given video track.
This is on purpose that the feature is available on desktop only. The hook code has been partially written by Claude and inspired by @sylvinus first suggestion.
> ✨(frontend) add fullscreen mode on desktop

- src/frontend/src/features/rooms/livekit/components/controls/SupportToggle.tsx
- src/frontend/src/features/support/hooks/useSupport.tsx
Prevents runtime error when Crisp chat hasn't initialized before component mount Previously caused crash since we assumed $crisp global was always available.
> 🩹(frontend) prevent runtime error when Crisp is not initialized

- src/frontend/src/features/rooms/livekit/components/controls/Options/EffectsMenuItem.tsx
Align effects icon with the one from the newly refactored pre-join screen. This new icon is stylish.
To be merged after #309
> 🚸(frontend) replace effects icons in menu option

- src/frontend/src/features/support/hooks/useSupport.tsx
Some users have ad-blockers or privacy extensions that prevent the Crisp chat widget script from loading properly. This was causing the support toggle to still display in rooms, but clicking it had no effect since Crisp was blocked.
This ensures users don't see an inactive support button when their browser is blocking Crisp functionality.
Issue reported by @felhix
> 🩹(frontend) prevent support toggle when Crisp chat is blocked by browsers

- src/frontend/panda.config.ts
- src/frontend/src/features/rooms/livekit/components/effects/EffectsConfiguration.tsx
- src/frontend/src/hooks/useSyncAfterDelay.ts
- src/frontend/src/primitives/Loader.tsx
- src/frontend/src/primitives/buttonRecipe.ts
https://github.com/user-attachments/assets/ecda3e64-56a5-4090-8f72-8718652b1f04
`useSyncAfterDelay` allows to enable loading indicators only if the loading takes more than a specific time. It prevent blinking effect when the loading time is nearly instant. 
Loading effects:
- Loader on video
- Disable effect on effects buttons
Please see below
https://github.com/user-attachments/assets/43642734-d2dd-40d6-b46e-7ab59502ae13
> ✨(front) turn on camera when applying effects

- src/frontend/src/locales/fr/settings.json
Typo identified by Celine. No "e" in french.
> ✏️(frontend) fix minor typo

- .github/workflows/release-helm-chart.yaml
- CHANGELOG.md
- src/helm/meet/Chart.yaml
- src/helm/meet/README.md
- src/helm/meet/templates/backend_deployment.yaml
- src/helm/meet/templates/celery_deployment.yaml
- src/helm/meet/templates/frontend_deployment.yaml
- src/helm/meet/templates/summary_deployment.yaml
- src/helm/meet/values.yaml
In order to avoid a service interruption during a Kubernetes (k8s) upgrade, we add a Pod Disruption Budget (PDB) to deployments.
> ✨(helm) add pdbs to deployments

- src/frontend/src/features/notifications/MainNotificationToast.tsx
- src/frontend/src/features/notifications/NotificationDuration.ts
- src/frontend/src/features/notifications/NotificationType.ts
- src/frontend/src/features/notifications/components/ToastLowerHand.tsx
- src/frontend/src/features/notifications/components/ToastRegion.tsx
- src/frontend/src/features/notifications/utils.ts
- src/frontend/src/features/rooms/livekit/components/controls/HandToggle.tsx
- src/frontend/src/locales/de/notifications.json
- src/frontend/src/locales/en/notifications.json
- src/frontend/src/locales/fr/notifications.json
Users requested that their raised hands be lowered automatically if they become the active speaker. This change ensures a more natural experience during discussions, preventing users from forgetting to lower their hand while speaking.
[Demo](https://www.loom.com/share/6794f906df2149498f7ea4933237f0f5)
> lower hand autonomously for active speakers

- src/frontend/src/features/notifications/components/ToastMessageReceived.tsx
- src/frontend/src/primitives/Text.tsx
Minor issue, layout overflow occurred when sharing url or long text.
> 🩹(frontend) fix text overflow in message notification

- src/frontend/src/features/rooms/components/Rating.tsx
Visual regression was introduced probably by a change on button style. As this button is quite different than the usual one, remove its inheritance from the primitive ones.
> 🩹(frontend) fix visual regression on Ratings buttons

- .github/workflows/docker-hub.yml
Argocd deployment use numerique-gouv/lasuite-deploiement as source so the webhook need to tell argocd to refresh apps that use this repos
> 🔧(ci) fix argocd notification

- src/frontend/src/features/rooms/livekit/components/FullScreenShareWarning.tsx
- src/frontend/src/locales/en/rooms.json
- src/frontend/src/locales/fr/rooms.json
This feature is far from perfect. Still not working on Safari. Also, we should display this warning when user shares the current opened window. Minor enhancement, I don't have time currently to prioritize these enhancements.
I've listed enhancements here : #355
> 🩹(frontend) fix screen sharing warnings browser compatibility

- src/frontend/src/features/rooms/livekit/components/effects/EffectsConfiguration.tsx
Based on user feedbacks, allow them stopping an effect explicitly by pressing a "no effect" option.
There is still a rendering issue, but the root cause is deeper than the EffectsConfiguration, I'll address it in a dedicated PR.
> 🚸(frontend) offer a "clear effect" option

- src/frontend/src/features/notifications/MainNotificationToast.tsx
The notifications namespace was being lazy-loaded when the first notification appeared, causing a screen flicker during translation loading. Now preloading the namespace during i18n initialization to ensure smooth rendering.
> 🩹(frontend): preload notifications translations to prevent flickering

- src/frontend/src/features/rooms/livekit/components/controls/ReactionsToggle.tsx
Emojis are a constant, so the reaction index remains stable, but using the index as a key isn't ideal.
> 🩹(frontend) fix missing key in reactions toolbar

- bin/Tiltfile
Tilt live updates generate a new image for each change, ending up storing a lot of images when you are really developing with Tilt.
I have not found a built-in way of cleaning old images from Tilt documentation, I create a utility doing the dirty work.
> ⚡️(tilt) clean automatically old images

- src/frontend/src/features/rooms/livekit/components/controls/ReactionsToggle.tsx
Fix this minor accessibility issue. Reaction wasn't accessible using keyboard. Sill imperfect, if you move focus outside of the toolbar, you won't be able to retrieve it.
> ♿️(frontend) autofocus the reaction toolbar on open

- src/frontend/src/features/rooms/livekit/components/chat/Entry.tsx
Add CSS styling to preserve return lines and whitespace in chat messages, fixing display issues that were causing broken line formatting.
> 🐛(frontend) preserve line breaks and whitespace in chat messages

- src/helm/env.d/dev-keycloak/values.meet.yaml.gotmpl
Replace invalid session/end endpoint with correct logout endpoint in Keycloak configuration. Fixes broken logout functionality that prevented developers from properly signing out of the application during development.
It closes #281
> 🐛(frontend) correct Keycloak logout endpoint in tilt stack

- src/frontend/src/App.tsx
- src/frontend/src/components/NotFoundScreen.tsx
- src/frontend/src/locales/de/global.json
- src/frontend/src/locales/en/global.json
- src/frontend/src/locales/fr/global.json
Make the page not found accessible (again).
With the recent release, the page not found mechanism was broken :
Also enhance the error message based on @sampaccoud's suggestion.
> Fix Page not found

- src/frontend/src/features/notifications/MainNotificationToast.tsx
- src/frontend/src/features/rooms/livekit/components/controls/ReactionsToggle.tsx
A participant could send a forbidden emoji by using their LiveKit access token to obtain a LiveKit client and transmit data to other participants. Prevent this from happening.
> Enhance Reactions Toolbar security

- src/frontend/src/features/rooms/livekit/components/SidePanel.tsx
Fix regression caused by competing styling methods in Box component. Remove duplicate position properties and standardize on simple div with css-in-js approach to prevent style conflicts and unexpected layout behavior.
> 🐛(frontend) resolve conflicting styling approaches in SidePanel component

- src/frontend/Dockerfile
Fixed two HIGH severity vulnerabilities in libxslt:
- CVE-2024-55549: Use-After-Free in libxslt (xsltGetInheritedNsList)
- CVE-2025-24855: Use-After-Free in libxslt numbers.c
The image was manually updated as no more recent unprivileged nginx-based images were available. This addresses the security scan failures from Trivy.
> 🔒️(frontend) update meet-frontend image to address security vulnerabilities

- src/frontend/src/features/rooms/livekit/components/ScreenShareErrorModal.tsx
- src/frontend/src/features/rooms/livekit/prefabs/VideoConference.tsx
- src/frontend/src/locales/de/rooms.json
- src/frontend/src/locales/en/rooms.json
- src/frontend/src/locales/fr/rooms.json
- src/frontend/src/locales/nl/rooms.json
Created modal that appears when users fail to share their entire screen. Also added documentation helper that explains proper screen sharing setup steps for different operating systems and browsers.
https://github.com/user-attachments/assets/e5202e38-c538-45b8-8f1f-736c632aa71f
> 🚸(frontend) add screen sharing troubleshooting modal and setup guide

- src/frontend/src/locales/fr/rooms.json
Based on Users' feedbacks. Also based on Arnaud's one, avoid having a double negation for the public restriction.
> ✏️(frontend) fix typos in the admin side panel

- LICENSE.md
Duplicate the MIT License, which are not yet supported by GitHub and its badges.
> 🐛(license) fix reuse.software missing support in GitHub

- src/frontend/src/features/rooms/livekit/components/effects/Effects.tsx
Since refactoring, the effect side panel, was not scrollable anymore. Fixed it.
> 🐛(frontend) fix effect menu scroll

- src/backend/core/services/lobby.py
Invert operation sequence to first notify people in room before setting participant in cache. Fixes infinite loop issue caused by 3s cache timeout for waiting participants when requests take too long. Problem only occurred when notifications were delayed, as faster notification delivery masked the race condition.
> 🩹(backend) invert operation order in participant handling

- src/backend/meet/settings.py
Ignore logs from DockerflowMiddleware
and minimize unnecessary log submissions.
> 🔇(backend) reduce noisy logs in Sentry

- src/backend/core/authentication/backends.py
- src/backend/meet/settings.py
This change allows the marketing service timeout to be easily adjusted via an environment variable, eliminating the need for a new software release. Additionally, the update makes the code more explicit and easier to maintain.
> ✨(backend) add env variable to configure marketing service timeout

- LICENSE.md
The project has started in 2024 and it is still active in 2025.
Yeah, it is not the most important commit of the repository 😅. 
I just found a bit weird to have these dates in the LICENCE file, and I thought it might be interesting to fix them.
Feel free to close if you disagree, I won't bother.
> 🐛(licence) fix the copyright years in licence

- src/summary/summary/core/celery_worker.py
Wrong syntaxt to handle bold, instead was italic.
> 🩹(summary) fix bold markdown syntax

- src/frontend/src/features/sdk/routes/CreateMeetingButton.tsx
- src/frontend/src/features/sdk/utils/PopupManager.ts
On the first room creation, the iframe wasn't properly messaging the parent. Fixed it. Send the room data in any of the two methods to acquire it.
> 🩹(sdk) notify iframe parent when room is gathered through callback

- src/backend/pyproject.toml
We have the dependency url-normalize installed but we don't use it in our codebase.
(from @lunika on docs)
> ➖(back) remove url-normalize dependency

- env.d/development/common.dist
- src/backend/core/recording/event/notification.py
- src/backend/core/tests/recording/event/test_notification.py
- src/backend/locale/en_US/LC_MESSAGES/django.po
- src/backend/locale/fr_FR/LC_MESSAGES/django.po
- src/backend/meet/settings.py
- src/helm/env.d/dev-keycloak/values.meet.yaml.gotmpl
- src/helm/env.d/dev/values.meet.yaml.gotmpl
- src/mail/mjml/screen_recording.mjml
Implement backend method to send email notifications when screen recordings are ready for download. Enables users to be alerted when their recordings are available. Frontend implementation to follow in upcoming commits.
This service is triggered by the storage hook from Minio.
Add minimal unit test coverage for notification service, addressing previous lack of tests in this area. The notification service was responsible for calling the unstable summary service feature, which was developped way too quickly.
The email template has been reviewed by a LLM, to make it user-friendly and crystal clear.
> ✨(backend) add email notifications for screen recordings

- .github/workflows/meet.yml
- compose.yml
- env.d/development/common.dist
- src/backend/core/api/serializers.py
- src/backend/core/api/viewsets.py
- src/backend/core/enums.py
- src/backend/core/models.py
- src/backend/core/recording/enums.py
- src/backend/core/recording/event/notification.py
- src/backend/core/recording/worker/services.py
- src/backend/core/tests/recording/test_api_recordings_list.py
- src/backend/core/tests/recording/test_api_recordings_media_auth.py
- src/backend/core/tests/recording/test_api_recordings_retrieve.py
- src/backend/core/tests/test_models_recording.py
- src/backend/core/utils.py
- src/backend/pyproject.toml
- src/helm/env.d/dev-keycloak/values.meet.yaml.gotmpl
- src/helm/env.d/dev/values.meet.yaml.gotmpl
- src/helm/meet/README.md
- src/helm/meet/templates/ingress_media.yaml
- src/helm/meet/templates/media_svc.yaml
- src/helm/meet/values.yaml
Enable users to download their recordings seamlessly.
Taking inspiration from the approach used in Docs, this proposal introduces a new endpoint to support recording downloads. To enable the frontend to render a complete information page, additional metadata has been added to the recording serializer.
Looking ahead, both this page and the media endpoint could eventually be replaced by Fichier for a more unified file access experience.
In a future V2, we’ll introduce automatic expiration of recordings after 7 days — stay tuned!
> Support media link to download recording

- src/frontend/src/features/notifications/components/WaitingParticipantNotification.tsx
Add a sound notification while a participant is waiting in the lobby. KISS, use the same notification as the one when participant join the room, thus, without any extra works, user can already toggle the notification in settings.
In a v2, a dedicated notification could be added.
Requested by a user.
It closes #449
> 🚸(frontend) add sound notification for lobby

- src/backend/meet/settings.py
- src/frontend/src/api/useConfig.ts
- src/frontend/src/features/auth/api/useUser.tsx
Implement configuration option in backend to enable or disable silent login functionality. Provides flexibility to control this authentication behavior through server settings.
Requested by user self-hosting the project. Not all OIDC provider support prompt=none param.
It closes #459
> 🔧 (backend) add backend toggle for silent login feature

- env.d/development/common.dist
- src/backend/core/api/permissions.py
- src/backend/core/api/serializers.py
- src/backend/core/api/viewsets.py
- src/backend/core/services/invitation.py
- src/backend/core/tests/rooms/test_api_rooms_invite.py
- src/backend/meet/settings.py
- src/helm/env.d/dev-keycloak/values.meet.yaml.gotmpl
- src/helm/env.d/dev/values.meet.yaml.gotmpl
- src/mail/mjml/invitation.mjml
Feature requested by some users. 
Being able to send email invitation from a room. (Inspired by proprietary solutions)
Frontend will display a pop-in with email selection / search. 
Frontend will be responsible to call the /invite endpoint to trigger the email, and add the invited people to the room as member, if they exist in our user base (we don't have pending invitation mechanism as on docs).
This frontend feature will be added in a next PR. 
This new endpoint is intentionally minimal and simply handles sending emails to all invited users. I haven’t added unit tests for the service, as I’m relying on integration tests at the viewset level instead. Feel free to challenge the implementation — I shipped it fast
> Invite people by email

- src/frontend/panda.config.ts
- src/frontend/src/features/rooms/livekit/components/Info.tsx
- src/frontend/src/features/rooms/livekit/components/SidePanel.tsx
- src/frontend/src/features/rooms/livekit/components/controls/InfoToggle.tsx
- src/frontend/src/features/rooms/livekit/hooks/useSidePanel.ts
- src/frontend/src/features/rooms/livekit/prefabs/ControlBar/MoreOptions.tsx
- src/frontend/src/locales/de/rooms.json
- src/frontend/src/locales/en/rooms.json
- src/frontend/src/locales/fr/rooms.json
- src/frontend/src/locales/nl/rooms.json
- src/frontend/src/primitives/Text.tsx
Implement new side panel that provides easy access to meeting information with copy/paste capabilities. Introduces xs text size to accommodate longer URLs. Panel includes space for future documentation links about meeting functionality. Addresses direct user requests for simpler sharing of meeting details.
> ✨(frontend) add meeting info side panel with copy functionality

- src/backend/core/models.py
- src/backend/core/tests/test_models_recording.py
Modify media auth endpoint to properly handle recordings with "Notification succeeded" status alongside "Saved" status. Previous code incorrectly expected only "Saved" status, causing access issues after email notifications were sent and status was updated.
> 🐛(backend) update media auth endpoint to check correct recording status

- src/frontend/src/features/auth/api/useUser.tsx
- src/frontend/src/features/recording/routes/RecordingDownload.tsx
Fix UI flickering where authentication screen briefly appeared for logged-in users during initial data loading. Address issue caused by increased request delay from waterfall cascade introduced by configurable silent auth setting.
> 🚸(frontend) prevent authentication screen flashing during user data fetch

- src/backend/meet/settings.py
Add environment variable to control data directory location when building outside of Docker. Improves flexibility for non-containerized deployments where storing data at filesystem root is inappropriate or undesirable.
the env variable will be prefixed by `DJANGO_` @fflorent .
> 🔧(backend) make data directory location configurable via env var

- src/frontend/src/features/rooms/livekit/components/ParticipantName.tsx
- src/frontend/src/features/rooms/livekit/components/ParticipantTile.tsx
- src/frontend/src/locales/de/rooms.json
- src/frontend/src/locales/en/rooms.json
- src/frontend/src/locales/fr/rooms.json
- src/frontend/src/locales/nl/rooms.json
Component now supports i18n. The participant tile needs further refactoring as it still mixes LiveKit CSS with custom styling.
It closes #485
> ♻️(frontend) refactor ParticipantName component for internationalization

- src/backend/core/api/serializers.py
- src/backend/core/api/viewsets.py
- src/backend/core/tests/rooms/test_api_rooms_retrieve.py
- src/backend/meet/settings.py
Respond to YesWeHack reports:
- Report #YWH-PGM14336-4
- Report #YWH-PGM14336-5
Goal:
- Ensure members are not trusted by default; do not expose the list of accessible resources to room members.
- Disable the browsable API to prevent leakage of sensitive information.
> YWH reports 

- src/backend/core/recording/worker/services.py
- src/frontend/src/features/recording/api/startRecording.ts
- src/frontend/src/features/recording/api/stopRecording.ts
- src/frontend/src/features/recording/components/ScreenRecordingSidePanel.tsx
- src/frontend/src/features/recording/components/TranscriptSidePanel.tsx
- src/frontend/src/locales/de/rooms.json
- src/frontend/src/locales/en/rooms.json
- src/frontend/src/locales/fr/rooms.json
- src/frontend/src/locales/nl/rooms.json
Implement broad exception handling to catch any non-twirp errors
during recording operations. Ensures recording status is properly reset to
"failed to start" when errors occur, allowing users to retry the recording
while still logging errors to Sentry for investigation.
It's generally a bad practice, however in this case it's fine, I am
catching exception beforehand and it only acts as a fallback.
> 🥅(backend) add broad exception handling for non-twirp errors in recording

- src/frontend/src/features/recording/components/ScreenRecordingSidePanel.tsx
- src/frontend/src/features/recording/components/TranscriptSidePanel.tsx
Block recording and transcript features when user isn't connected to prevent database state corruption. Users were previously able to trigger these actions despite being disconnected.
> 🔒️(frontend) prevent disconnected users from accessing recording tools

- src/backend/core/authentication/backends.py
- src/backend/core/recording/event/authentication.py
- src/backend/locale/de_DE/LC_MESSAGES/django.po
- src/backend/locale/en_US/LC_MESSAGES/django.po
- src/backend/locale/fr_FR/LC_MESSAGES/django.po
- src/backend/locale/nl_NL/LC_MESSAGES/django.po
Some backend translations were wrongly internationalized, as not user facing.
Fix those issues.
> Remove useless translation in the backend

- src/backend/core/models.py
The idea behind wrapping choices in `lazy` function was to allow overriding the list of languages in tests with `override_settings`. This was causing makemigrations to keep on including the field in migrations when it is not needed. Since we finally don't override the LANGUAGES setting in tests, we can remove it to fix the problem.
Taken from docs #c882f13
> ♻️(backend) remove lazy from languages field on User model

- src/helm/meet/Chart.yaml
- src/helm/meet/templates/ingress.yaml
Replace generic '/api' path with versioned '/api/v' pattern in Helm ingress template to ensure proper routing for backend requests.
It closes #539
> 🐛(backend) fix ingress path to use specific API path

- docs/installation.md
Add critical setup requirements including kubectl installation, script download instructions, executable permissions for mkcert and Docker, and clarify local-only access limitation.
> 📝(backend) improve kind deployment documentation with missing prerequisites

- src/frontend/src/components/AppInitialization.tsx
Fix issue where user language preferences stopped properly syncing between frontend and backend, causing inconsistent language experience. Issue was reported by user and affected localization settings persistence.
> 🐛(frontend) restore user language synchronization between frontend and backend

- src/backend/meet/settings.py
Correct spelling in environment variable name as identified by @K900. This is technically a breaking change for existing deployments using this setting, but acceptable as we haven't released an official version yet. Will personally notify known users of this setting about the change to minimize disruption.
It closes #556
> ✏️(backend) fix typo in FRONTEND_IS_SILENT_LOGIN_ENABLED env var

- src/frontend/package-lock.json
- src/frontend/package.json
Downgrade @livekit/components-js due to bug introduced in version 2.9.0. Issue has been reported to upstream maintainers at: https://github.com/livekit/components-js/issues/1158
Reverting to last known stable version until fix is available.
> ⬇️(frontend) rollback LiveKit component library from 2.9.0 to 2.8.1

- src/helm/meet/Chart.yaml
- src/helm/meet/templates/ingress.yaml
The current path is `/api/v`, and it doesn't work with `ingress-nginx`. I'm not sure if other ingress controllers work with this prefix, but changing it to `/api/` will work for `ingress-nginx` and likely for others as well.
please refer to original PR #554
> 🔧(helm) fix the path of the backend ingress.

- src/frontend/default.conf
Remove version disclosure in `/assets/` error pages identified by security auditor to prevent information leakage vulnerability.
> 🔒️(frontend) hide Nginx server version in error responses

- src/frontend/src/features/rooms/livekit/hooks/useConnectionObserver.ts
- src/frontend/src/features/rooms/livekit/prefabs/VideoConference.tsx
Track connection issues to identify user problems. Skip client-initiated disconnects (normal flow). Disconnect events provide richer data than reconnect events which lack reason details.
Next: Add error screen for JOIN_FAILURE disconnects to trigger support workflow for users experiencing connection problems.
> 📈(frontend) add analytics for disconnect/reconnect events

- env.d/development/common.dist
Correct OIDC_REDIRECT_ALLOWED_HOSTS configuration that was preventing proper URL validation. Thanks to @nvasse for identifying and fixing the issue.
Note: Update your common env file with corrected values.
> 🐛(backend) fix OIDC returnTo parameter validation in Docker compose

- .github/workflows/meet.yml
- Dockerfile
- src/helm/env.d/dev-keycloak/values.meet.yaml.gotmpl
- src/helm/env.d/dev/values.meet.yaml.gotmpl
- src/summary/Dockerfile
Python 3.13 is now stable, our libraries are compatible with it. We also
upgrade the alpine version and node one used in the backend.
> ⬆️(docker) upgrade backend image to python 3.13

- src/summary/summary/core/analytics.py
- src/summary/summary/core/celery_config.py
- src/summary/summary/core/celery_worker.py
Forgot to update the args verification while enriching the task with more recording metadata
> 🐛(summary) fix Celery task execution by number of required args

- src/frontend/src/features/settings/components/SettingsDialogExtended.tsx
- src/frontend/src/features/settings/components/tabs/AudioTab.tsx
- src/frontend/src/locales/de/settings.json
- src/frontend/src/locales/en/settings.json
- src/frontend/src/locales/fr/settings.json
- src/frontend/src/locales/nl/settings.json
- src/frontend/src/primitives/Text.tsx
- Switch to useMediaQuery to avoid weird styling of seetings on mobile.
- Add a warning explaining why speakers are note available on Safari.
> Improve mobile settings (sizing and Safari audio output warning)

- src/frontend/src/features/rooms/components/Conference.tsx
Replace custom connection warmup implementation with LiveKit's built-in methods for better reliability and consistency.
> ♻️(frontend) refactor connection warmup to use LiveKit methods

- docs/examples/meet.values.yaml
- docs/installation.md
- src/helm/env.d/dev-dinum/values.meet.yaml.gotmpl
- src/helm/env.d/dev-keycloak/values.meet.yaml.gotmpl
- src/helm/env.d/dev/values.meet.yaml.gotmpl
Yesterday during a deployment, we discovered that these variables are unused:
POSTGRES_DB
POSTGRES_USER
POSTGRES_PASSWORD
> ♻️(documentation) remove unused environment variables

- src/helm/meet/Chart.yaml
- src/helm/meet/README.md
- src/helm/meet/templates/ingress.yaml
- src/helm/meet/templates/ingress_admin.yaml
- src/helm/meet/templates/ingress_posthog.yaml
- src/helm/meet/templates/ingress_posthog_assets.yaml
- src/helm/meet/values.yaml
Yesterday during a deployment, we were unable to configure the tls secretName for ingress.
> ✨(helm) add the ability to configure tls secretName

- src/frontend/src/features/rooms/components/Join.tsx
- src/frontend/src/features/rooms/livekit/hooks/useResolveInitiallyDefaultDeviceId.ts
Replace usePreviewTrack approach with manual track management inspired by deprecated LiveKit implementation that only toggles what's needed instead of resetting entire preview track on config changes.
Previous approach created new videoTrack when updating audio track, causing video preview to blink black during audio configuration changes.
It was also acquiring video streams even when disabled.
New implementation:
* Initializes tracks once with user permissions for both devices
* Manually handles muting/unmuting and device updates
* Preserves muted state when changing device IDs
* Uses exact device constraints on Chrome for proper device selection
Prevents unnecessary track recreation and eliminates preview blinking.
> ♻️(frontend) refactor preview track to avoid unnecessary resets

- .github/workflows/meet.yml
Implement pip dependency caching across all CI jobs requiring package installation and upgrade actions/setup-python from v4 to v5.
The setup-python action is able to cache the dependencies and reuse this cache while the pyproject file has not changed. It is easy to setup, just the package manager used has to be declared in the cache settings
> 👷(ci) add pip caching and upgrade setup-python action to v5

- src/backend/core/utils.py
Configure LiveKit token to explicitly allow users to subscribe to other participants' video and audio tracks instead of relying on default permissions.
> 🔧(backend) set explicit user subscription permissions for other tracks

- src/backend/core/api/feature_flag.py
- src/backend/core/api/permissions.py
- src/backend/core/api/viewsets.py
- src/backend/core/tests/recording/test_api_recordings_storage_hook.py
- src/backend/core/tests/rooms/test_api_rooms_start_recording.py
- src/backend/core/tests/rooms/test_api_rooms_stop_recording.py
- src/backend/core/tests/rooms/test_api_rooms_subtitle.py
Refactor feature flag mechanism from Django permission classes to custom decorator that returns 404 Not Found when features are disabled instead of exposing API structure through permission errors.
Improves security by preventing information disclosure about disabled features and provides more appropriate response semantics. Custom decorator approach is better suited for feature toggling than Django's permission system which is designed for authorization.
> ♻️(backend) replace Django permissions with custom feature flag decorator

- docker/livekit/Dockerfile
Update development environment LiveKit server from previous version to 1.9.0 for latest features and bug fixes.
Ensures development environment stays current
with LiveKit production version.
> ⬆️(livekit) upgrade local LiveKit server to version 1.9.0

- src/backend/core/recording/event/notification.py
- src/summary/summary/api/route/tasks.py
- src/summary/summary/core/celery_worker.py
fix the featureflag to allow chosen users to use
the summary feature by using the owner_id instead of sub because 
users are identified with owner_id as distinct_id in posthog. It's necessary
to use the distinct_id to check the feature flag.
> 🐛(summary) fix featureflag

- src/backend/pyproject.toml
Resolve vulnerability CVE-2025-59681, that triggers Trivy scan and block PR's merging.
More information there https://avd.aquasec.com/nvd/cve-2025-59681
> ⬆️(backend) upgrade django to 5.2.7
